# =============================================================================
#
#  FILE:
#    Src_DSFxp.mk
#
#  DESCRIPTION:
#    MAKE-file fragment containing a source file list for the generic library
#      DSfxp.lib
#
#
#  REMARKS:
#
#  AUTHOR(S):
#    o. Grajetzky
#
#  Copyright (c) 1999 dSPACE GmbH, GERMANY
#
#  $Workfile: Src_DSFxp.mk $ $Revision: 12 $ $Date: 30.07.03 13:13 $ $Author: Klausg $
# =============================================================================

SRC_DSFXP = \
    $(SRCFILES_PATH)\Generic\DSFxp\ASIN_02.c \
    $(SRCFILES_PATH)\Generic\DSFxp\ATAN_01.c \
    $(SRCFILES_PATH)\Generic\DSFxp\ATAN_02.c \
    $(SRCFILES_PATH)\Generic\DSFxp\COS_04.c \
    $(SRCFILES_PATH)\Generic\DSFxp\COS_05.c \
    $(SRCFILES_PATH)\Generic\DSFxp\COS_06.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV48s01.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64_01.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64_02.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64_03.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64_04.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64_05.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64_06.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64_07.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64_08.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64s01.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64s02.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64s03.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64s04.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64s05.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64s06.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64s07.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64s08.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64s09.c \
    $(SRCFILES_PATH)\Generic\DSFxp\DIV64s10.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_000.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_100.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_101.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_111.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_200.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_201.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_202.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_211.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_212.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_222.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_300.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_301.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_302.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_311.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_312.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_322.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_444.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_544.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_545.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_555.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_644.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_645.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_646.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_655.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_656.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_666.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_744.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_745.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_746.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_755.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_756.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_766.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_888.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR0_999.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_000.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_100.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_101.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_111.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_200.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_201.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_202.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_211.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_212.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_222.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_300.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_301.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_302.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_311.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_312.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_322.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_444.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_544.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_545.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_555.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_644.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_645.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_646.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_655.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_656.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_666.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_744.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_745.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_746.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_755.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_756.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR1_766.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_000.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_100.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_101.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_111.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_200.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_201.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_202.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_211.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_212.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_222.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_300.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_301.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_302.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_311.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_312.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_322.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_444.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_544.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_545.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_555.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_644.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_645.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_646.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_655.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_656.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_666.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_744.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_745.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_746.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_755.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_756.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_766.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_888.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR2_999.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_000.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_100.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_101.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_111.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_200.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_201.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_202.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_211.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_212.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_222.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_300.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_301.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_302.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_311.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_312.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_322.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_444.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_544.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_545.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_555.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_644.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_645.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_646.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_655.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_656.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_666.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_744.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_745.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_746.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_755.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_756.c \
    $(SRCFILES_PATH)\Generic\DSFxp\FIR3_766.c \
    $(SRCFILES_PATH)\Generic\DSFxp\LUTCOS.c \
    $(SRCFILES_PATH)\Generic\DSFxp\MUL64_01.c \
    $(SRCFILES_PATH)\Generic\DSFxp\MUL64_02.c \
    $(SRCFILES_PATH)\Generic\DSFxp\MUL64_03.c \
    $(SRCFILES_PATH)\Generic\DSFxp\MUL64_04.c \
    $(SRCFILES_PATH)\Generic\DSFxp\MUL64_05.c \
    $(SRCFILES_PATH)\Generic\DSFxp\MUL64s01.c \
    $(SRCFILES_PATH)\Generic\DSFxp\MUL64s02.c \
    $(SRCFILES_PATH)\Generic\DSFxp\MUL64s03.c \
    $(SRCFILES_PATH)\Generic\DSFxp\NEG64s01.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SIN_01.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SIN_04.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SIN_05.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SIN_06.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SIN_07.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SIN_08.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SIN_09.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SIN_10.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SIN_11.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_01.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_02.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_03.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_04.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_05.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_06.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_07.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_08.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_09.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_10.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_11.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_12.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_13.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_14.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_15.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_16.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_17.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_18.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_19.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_20.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_21.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_22.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_23.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_24.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_25.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_26.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_27.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_28.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_29.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_30.c \
    $(SRCFILES_PATH)\Generic\DSFxp\SQRT_31.c \
    $(SRCFILES_PATH)\Generic\DSFxp\TAN_01.c \
    $(SRCFILES_PATH)\Generic\DSFxp\TAN_01a.c \
    $(SRCFILES_PATH)\Generic\DSFxp\TAN_07.c \
    $(SRCFILES_PATH)\Generic\DSFxp\TAN_07a.c \
    $(SRCFILES_PATH)\Generic\DSFxp\TAN_08.c \
    $(SRCFILES_PATH)\Generic\DSFxp\TAN_08a.c \
    $(SRCFILES_PATH)\Generic\DSFxp\TAN_09.c \
    $(SRCFILES_PATH)\Generic\DSFxp\TAN_09a.c \
    $(SRCFILES_PATH)\Generic\DSFxp\TAN_10.c \
    $(SRCFILES_PATH)\Generic\DSFxp\TAN_10a.c \
    $(SRCFILES_PATH)\Generic\DSFxp\TAN_11.c \
    $(SRCFILES_PATH)\Generic\DSFxp\TAN_11a.c
    