/**************************************************************************************************\
 *** 
 *** Simulink model       : BVH2_App_Layer
 *** TargetLink subsystem : BVH2_App_Layer/BVH2_Appl_Layer
 *** Codefile             : bvh2_appl_layer.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2015-06-22 15:49:17
 ***
 *** CODE GENERATOR OPTIONS:
 *** Compiler                            : <unknown>
 *** Target                              : Generic
 *** ANSI-C compatible code              : yes
 *** Optimization level                  : 2
 *** Constant style                      : decimal
 *** Clean code option                   : enabled
 *** Logging mode                        : Do not log anything
 *** Linker sections                     : enabled
 *** Assembler statements                : disabled
 *** Variable name length                : 31 chars
 *** Separate lookup search function     : disabled
 *** Use global bitfields                : disabled
 *** Stateflow: use of bitfields         : enabled
 *** State activity encoding limit       : 5
 *** Omit zero inits in restart function : disabled
 *** Share fcns between TL subsystems    : disabled
 *** Generate 64bit functions            : enabled
 *** Inlining Threshold                  : 6
 *** Line break limit                    : 100
 *** Target optimized boolean data type  : enabled
 *** Keep saturation elements            : disabled
 *** Extended variable sharing           : disabled
 *** Style definition file               : C:\Programme\dSPACE\Matlab\Tl\config\codegen\cconfig.xml
 *** Root style sheet                    : C:\Programme\dSPACE\Matlab\Tl\XML\CodeGen\Stylesheets\TL_
 ***                                       CSourceCodeSS.xsl
 *** Enable Multirate codegeneration     : disabled
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sb1                      BVH2_App_Layer/BVH2_Appl_Layer
 *** Sb2                      BVH2_Appl_Layer/Controller
 *** Sb3                      BVH2_Appl_Layer/RangeAdaption
 *** Sb4                      BVH2_Appl_Layer/Controller/PID
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** Cb0       BVH2_App_Layer                                         
 *** Cb1       BVH2_Appl_Layer/Current_Analysis_High                  
 *** Cb1                                                              
 *** Cb2       BVH2_Appl_Layer/Current_Analysis_High.Reset            
 *** Cb3       BVH2_Appl_Layer/Current_Analysis_High.greenState       
 *** Cb4       BVH2_Appl_Layer/Current_Analysis_High.RestartCounter   
 *** Cb5       BVH2_Appl_Layer/Current_Analysis_High.Alarm_Off        
 *** Cb6       BVH2_Appl_Layer/Current_Analysis_High.Wait             
 *** Cb7       BVH2_Appl_Layer/Current_Analysis_High.CntOverCurrent   
 *** Cb8       BVH2_Appl_Layer/Current_Analysis_High.redState         
 *** Cb9       BVH2_Appl_Layer/Current_Analysis_low                   
 *** Cb9                                                              
 *** Cb9                                                              
 *** Cb9                                                              
 *** Cb9                                                              
 *** Cb9                                                              
 *** Cb9                                                              
 *** Cb10      BVH2_Appl_Layer/Current_Analysis_low.greenState        
 *** Cb11      BVH2_Appl_Layer/Current_Analysis_low.Wait              
 *** Cb12      BVH2_Appl_Layer/Current_Analysis_low.CntOverCurrent    
 *** Cb13      BVH2_Appl_Layer/Current_Analysis_low.redState          
 *** Cb14      BVH2_Appl_Layer/Dry_Running                            
 *** Cb14                                                             
 *** Cb14                                                             
 *** Cb15      BVH2_Appl_Layer/Dry_Running.greenState                 
 *** Cb16      BVH2_Appl_Layer/Dry_Running.DryRunning                 
 *** Cb17      BVH2_Appl_Layer/Dry_Running.DryRunning.redState        
 *** Cb18      BVH2_Appl_Layer/Dry_Running.DryRunning.CntOverCurrent  
 *** Cb19      BVH2_Appl_Layer/Dry_RunningAlarm                       
 *** Cb20      BVH2_Appl_Layer/Dry_RunningAlarm.greenState            
 *** Cb21      BVH2_Appl_Layer/Dry_RunningAlarm.DryRunningAlarm       
 *** Cb22      BVH2_Appl_Layer/Dry_RunningAlarm.DryRunningAlarm.DryRu
 ***           n66                                                    
 *** Cb23      BVH2_Appl_Layer/Dry_RunningAlarm.DryRunningAlarm.DryRu
 ***           n55                                                    
 *** Cb24      BVH2_Appl_Layer/Motor_Stalled                          
 *** Cb25      BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachi
 ***           ne                                                     
 *** Cb25                                                             
 *** Cb26      BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachi
 ***           ne.CntStart                                            
 *** Cb27      BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachi
 ***           ne.Speed_detection                                     
 *** Cb28      BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachi
 ***           ne.SpeedBad_cnt                                        
 *** Cb29      BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachi
 ***           ne.Motor_Run                                           
 *** Cb30      BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachi
 ***           ne.Motor_Wait                                          
 *** Cb31      BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachi
 ***           ne.Motor_Stalled                                       
 *** Cb32      BVH2_Appl_Layer/Motor_Stalled.default                  
 *** Cb33      BVH2_Appl_Layer/Motor_Stalled.Stop                     
 *** Cb34      BVH2_Appl_Layer/PWM_Detection                          
 *** Cb35      BVH2_Appl_Layer/PWM_Detection.PWMinput_handling        
 *** Cb35                                                             
 *** Cb36      BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.LimpMo
 ***           deLow                                                  
 *** Cb37      BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.LimpMo
 ***           deLow1                                                 
 *** Cb38      BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.Satura
 ***           tionHigh                                               
 *** Cb39      BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.Alarm  
 *** Cb40      BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.CMD_MJ
 ***           P_0_100                                                
 *** Cb41      BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.Normal
 ***           3                                                      
 *** Cb42      BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.Satura
 ***           tionLow                                                
 *** Cb43      BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.PumpOf
 ***           f2                                                     
 *** Cb44      BVH2_Appl_Layer/Pic_etat_monitor                       
 *** Cb45      BVH2_Appl_Layer/Pic_etat_monitor.Reset                 
 *** Cb46      BVH2_Appl_Layer/Pic_etat_monitor.greenState            
 *** Cb47      BVH2_Appl_Layer/Pic_etat_monitor.Alarm_Off             
 *** Cb48      BVH2_Appl_Layer/Pic_etat_monitor.Wait                  
 *** Cb49      BVH2_Appl_Layer/Pic_etat_monitor.Wrong_ETAT            
 *** Cb50      BVH2_Appl_Layer/Pic_etat_monitor.redState              
 *** Cb51      BVH2_Appl_Layer/Temperature_Alarm                      
 *** Cb51                                                             
 *** Cb51                                                             
 *** Cb51                                                             
 *** Cb52      BVH2_Appl_Layer/Temperature_Alarm.CntOverTemp          
 *** Cb53      BVH2_Appl_Layer/Temperature_Alarm.reset                
 *** Cb54      BVH2_Appl_Layer/Temperature_Alarm.greenTemp            
 *** Cb55      BVH2_Appl_Layer/Temperature_Alarm.redTemp              
 *** Cb56      BVH2_Appl_Layer/UbatHandling                           
 *** Cb57      BVH2_Appl_Layer/UbatHandling.Ubat_Handling             
 *** Cb57                                                             
 *** Cb57                                                             
 *** Cb57                                                             
 *** Cb57                                                             
 *** Cb58      BVH2_Appl_Layer/UbatHandling.Ubat_Handling.SaturationH
 ***           igh                                                    
 *** Cb59      BVH2_Appl_Layer/UbatHandling.Ubat_Handling.SaturationL
 ***           ow                                                     
 *** Cb60      BVH2_Appl_Layer/UbatHandling.Ubat_Handling.NormalUbat  
 *** 
 *** TargetLink version      : 2.0 from 22-Apr-2004
 *** Code generator version  : 2.0.0 build id 48 from 2004-04-22 13:23:03
 *** Copyright (c) 2004 dSPACE GmbH
\**************************************************************************************************/ 

#ifndef _BVH2_APPL_LAYER_C_
#define _BVH2_APPL_LAYER_C_

/*--------------------------------------------------------------------*\
  DEFINES (OPT)
\*--------------------------------------------------------------------*/
/*--------------------------------------------------------------------*\
  INCLUDES
\*--------------------------------------------------------------------*/
#include "dsfxp.h"
#include "BVH2_Appl_Layer.h"
/*--------------------------------------------------------------------*\
  DEFINES
\*--------------------------------------------------------------------*/

/**********************************************************************\
   TL_CG_MACROCL_GLOBALSrToLocal: TL CG ScopeReducedClass : derived from TL_CG_MACROCL_GLOBAL
\**********************************************************************/
#define Cb26_CntStart_id (UInt8)3 
#define Cb27_Speed_detection_id (UInt8)2 
#define Cb28_SpeedBad_cnt_id (UInt8)1 
#define Cb29_Motor_Run_id (UInt8)5 
#define Cb2_Reset_id (UInt8)6 
#define Cb30_Motor_Wait_id (UInt8)6 
#define Cb31_Motor_Stalled_id (UInt8)4 
#define Cb36_LimpModeLow_id (UInt8)3 
#define Cb37_LimpModeLow1_id (UInt8)8 
#define Cb38_SaturationHigh_id (UInt8)4 
#define Cb39_Alarm_id (UInt8)6 
#define Cb3_greenState_id (UInt8)3 
#define Cb40_CMD_MJP_0_100_id (UInt8)7 
#define Cb41_Normal3_id (UInt8)2 
#define Cb42_SaturationLow_id (UInt8)5 
#define Cb43_PumpOff2_id (UInt8)1 
#define Cb45_Reset_id (UInt8)4 
#define Cb46_greenState_id (UInt8)5 
#define Cb47_Alarm_Off_id (UInt8)3 
#define Cb48_Wait_id (UInt8)6 
#define Cb49_Wrong_ETAT_id (UInt8)2 
#define Cb4_RestartCounter_id (UInt8)7 
#define Cb50_redState_id (UInt8)1 
#define Cb5_Alarm_Off_id (UInt8)5 
#define Cb6_Wait_id (UInt8)4 
#define Cb7_CntOverCurrent_id (UInt8)2 
#define Cb8_redState_id (UInt8)1 

/*--------------------------------------------------------------------*\
  TYPEDEFS
\*--------------------------------------------------------------------*/
/*--------------------------------------------------------------------*\
  ENUMS
\*--------------------------------------------------------------------*/
/*--------------------------------------------------------------------*\
  VARIABLES
\*--------------------------------------------------------------------*/
/**********************************************************************\
   CONST: global constants (ROM)
\**********************************************************************/
CONST UInt16 Sb2_Fixed_Power = 202;

/**********************************************************************\
   GLOBAL: global variables (RAM)
\**********************************************************************/
GLOBAL UInt16 ui16_Current_Thresh;
GLOBAL UInt16 ui16_PWM_Freq_mat;
GLOBAL UInt16 ui16_Speed_demand_mat;
GLOBAL UInt16 ui16_Speed_demand_mat_Max;
GLOBAL UInt16 ui16_Speed_demand_mat_min;
GLOBAL UInt16 ui16_Speed_mat;
GLOBAL UInt16 ui16_dryRun_Thresh;
GLOBAL UInt16 ui16_mat_Current;
GLOBAL UInt16 ui16_mat_inpTemp;
GLOBAL UInt16 ui8_BattVolt_mat;
GLOBAL UInt16 ui8_Ki_mat;
GLOBAL UInt16 ui8_fixed_start_speed_mat;
GLOBAL Bool bl_Pumpoff_Alarm;
GLOBAL Bool bool_CPU_TempAlarm;
GLOBAL Bool bool_CPU_TempRedAlarm;
GLOBAL Bool bool_ControlLoopMode;
GLOBAL Bool bool_DryRunningAlarm;
GLOBAL Bool bool_HighCurrentAlarm;
GLOBAL Bool bool_MotorStalled;
GLOBAL Bool bool_PIC_Alarm;
GLOBAL Bool bool_PWMin_Freq_err_Alarm;
GLOBAL Bool bool_PWMin_err_Alarm;
GLOBAL Bool bool_StalledMotorStop;
GLOBAL Bool bool_UbatAlarm;
GLOBAL Bool bool_mat_currAlarm_bldc;
GLOBAL Bool bool_mat_pic_etat;
GLOBAL Bool bool_start_demand_mat;
GLOBAL UInt8 ui8_Kp_mat;
GLOBAL UInt8 ui8_PWM_dc_mat;
GLOBAL UInt8 ui8_ResetMatlab;
GLOBAL UInt8 ui8_debug_out0;
GLOBAL UInt16 ui16_duty_cycle_mat;

/**********************************************************************\
   SFStaticGlobalInit: Default storage class for global static variables with initial value
\**********************************************************************/
static UInt16 Cb1_StateCnt = 0;
static UInt16 Cb44_StateCnt = 0;
static UInt8 Cb1_RestartCounter = 0;

static struct tag_SIBFS_Current_Analysis_High_b_tp SIBFS_Current_Analysis_High_b = {
   0 /* Cb1_Current_Analysis_High_ns:  */, 
   0 /* Cb1_glflag:  */, 
   0 /* Cb1_Current_Analysis_High:  */
} /* Description: Structure containing bitfields for Stateflow chart  */;

static struct tag_SIBFS_PWM_Detection_b_tp SIBFS_PWM_Detection_b = {
   0 /* Cb35_PWMinput_handling_ns:  */, 
   0 /* Cb35_PWMinput_handling:  */
} /* Description: Structure containing bitfields for Stateflow chart  */;

static struct tag_SIBFS_Pic_etat_monitor_b_tp SIBFS_Pic_etat_monitor_b = {
   0 /* Cb44_Pic_etat_monitor_ns:  */, 
   0 /* Cb44_glflag:  */, 
   0 /* Cb44_Pic_etat_monitor:  */
} /* Description: Structure containing bitfields for Stateflow chart  */;

static struct tag_SIBFS_UbatHandling_b_tp SIBFS_UbatHandling_b = {
   0 /* Aux_sflag3:  */, 
   0 /* Cb57_Ubat_Handling:  */, 
   0 /* Cb58_SaturationHigh:  */, 
   0 /* Cb59_SaturationLow:  */, 
   0 /* Cb60_NormalUbat:  */
} /* Description: Structure containing bitfields for Stateflow chart  */;

/**********************************************************************\
   SLStaticGlobal: Default storage class for global static variables
\**********************************************************************/
static Bool Cb1_oCurrentAlarm = 0;
static Bool Cb1_oShutoff = 0;
static UInt8 Cb34_idPWM;
static Bool Cb34_oPWM_Alarm = 0;
static Bool Cb34_oPWM_SC_Alarm = 0;
static Bool Cb34_odFixedLowValueSel = 0;
static Bool Cb34_odFixedValueSel = 0;
static Bool Cb34_odPumpOff = 0;
static Bool Cb44_oAlarm = 0;
static Bool Cb44_oShutoff = 0;
static Bool Cb56_oUbat_Alarm_High = 0;
static Bool Cb56_odFixedValueSel = 0;
static Bool Cb56_odPumpOff = 0;
static Bool power_lockout = 0;
static UInt16 amps_per_volt_cnt = 0;

/*--------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*--------------------------------------------------------------------*/
/*--------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*--------------------------------------------------------------------*/
/**********************************************************************\
   StaticSFAux: Default function class for static stateflow auxiliary functions
\**********************************************************************/
static Void Cb1_Current_An___High_node_fcn1(Void);
static Void Cb34_PWM_Detection_node_fcn1(Void);
static Void Cb44_Pic_etat_monitor_node_fcn1(Void);
static Void Cb56_UbatHandling_node_fcn2(Void);

/*--------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*--------------------------------------------------------------------*/
/*--------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*--------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      BVH2_Appl_Layer
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      Void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/ 
Void BVH2_Appl_Layer(Void)
{
   /* SFStaticLocalInit: Default storage class for static local variables with initvalue */
   static UInt16 Cb14_StateCnt = 0;
   static UInt16 Cb19_Counter = 0;
   static UInt16 Cb24_BadCnt = 0;
   static UInt16 Cb24_StateCnt = 0;
   static UInt8 Cb24_RestartCounter = 0;
   static UInt8 Cb51_Counter = 0;
   static UInt8 Cb9_StateCnt = 0;
   
   static struct tag_SIBFS_Current_Analysis_low_b_tp SIBFS_Current_Analysis_low_b = {
      0 /* Cb10_greenState:  */, 
      0 /* Cb11_Wait:  */, 
      0 /* Cb12_CntOverCurrent:  */, 
      0 /* Cb13_redState:  */, 
      0 /* Cb9_Current_Analysis_low:  */
   } /* Description: Structure containing bitfields for Stateflow chart  */;
   
   static struct tag_SIBFS_Dry_RunningAlarm_b_tp SIBFS_Dry_RunningAlarm_b = {
      0 /* Cb19_Dry_RunningAlarm:  */, 
      0 /* Cb20_greenState:  */, 
      0 /* Cb21_DryRunningAlarm:  */, 
      0 /* Cb22_DryRun66:  */, 
      0 /* Cb23_DryRun55:  */
   } /* Description: Structure containing bitfields for Stateflow chart  */;
   
   static struct tag_SIBFS_Dry_Running_b_tp SIBFS_Dry_Running_b = {
      0 /* Cb14_Dry_Running:  */, 
      0 /* Cb15_greenState:  */, 
      0 /* Cb16_DryRunning:  */, 
      0 /* Cb17_redState:  */, 
      0 /* Cb18_CntOverCurrent:  */
   } /* Description: Structure containing bitfields for Stateflow chart  */;
   
   static struct tag_SIBFS_Motor_Stalled_b_tp SIBFS_Motor_Stalled_b = {
      0 /* Cb25_Motor_sta__Statemachine_ns:  */, 
      0 /* Cb24_glflag:  */, 
      0 /* Cb24_Motor_Stalled:  */, 
      0 /* Cb25_Motor_stalled_Statemachine:  */, 
      0 /* Cb32_default:  */, 
      0 /* Cb33_Stop:  */
   } /* Description: Structure containing bitfields for Stateflow chart  */;
   
   static struct tag_SIBFS_Temperature_Alarm_b_tp SIBFS_Temperature_Alarm_b = {
      0 /* Cb51_Temperature_Alarm:  */, 
      0 /* Cb52_CntOverTemp:  */, 
      0 /* Cb53_reset:  */, 
      0 /* Cb54_greenTemp:  */, 
      0 /* Cb55_redTemp:  */
   } /* Description: Structure containing bitfields for Stateflow chart  */;

   /* SLLocal: Default storage class for local variables */
   Int16 Sb2_Error;
   UInt16 Sb2_Switch2;
   UInt16 Sb2_Switch5;
   Bool Cb24_Reset;
   Bool Sb1_Logical_Operator1;
   Bool Sb1_Logical_Operator2;
   Bool Sb1_Logical_Operator3;
   Bool Sb1_Logical_Operator5;
   Bool Sb2_Logical_Operator2;

   /* SLStaticLocal: Default storage class for static local variables */
   static Bool Cb14_oDryRunAlarm = 0;
   static Bool Cb19_oDryRun55 = 0;
   static Bool Cb19_oDryRun66 = 0;
   static Bool Cb24_oMotorStalled = 0;
   static Bool Cb24_oStalledAlarm = 0;
   static Bool Cb51_oTempAlarm = 0;
   static Bool Cb51_oTempRedAlarm = 0;
   static Bool Cb51_odPumpOff = 0;
   static Bool Cb9_oCurrentAlarm = 0;

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue */
   static Int32 X_Sb4_Intergrator = 80000 /* 100. */ /* LSB: 0.00125 OFF:  0 MIN/MAX:  -2684354.56 .
   . 2684354.55875 */;
   static Bool Sb1_BVH2_Appl_Layer_FirstRun = 1;
   static Bool X_Sb4_Intergrator_TriggerIn = 1;

   // Begin execution of chart BVH2_Appl_Layer/Pic_etat_monitor
   switch (SIBFS_Pic_etat_monitor_b.Cb44_Pic_etat_monitor_ns) {
      case Cb45_Reset_id: {
         // Begin execution of state BVH2_Appl_Layer/Pic_etat_monitor.Reset
         if (Cb44_StateCnt > 50) {
            // State transition from BVH2_Appl_Layer/Pic_etat_monitor.Reset to BVH2_Appl_Layer/Pic_e
            //tat_monitor.greenState
            SIBFS_Pic_etat_monitor_b.Cb44_Pic_etat_monitor_ns = (unsigned int) Cb46_greenState_id;
            Cb44_oShutoff = 0;
            Cb44_oAlarm = 0;
            Cb44_StateCnt = 0;
         }
         else {
            Cb44_StateCnt = Cb44_StateCnt + 1;
         }

         // End execution of state BVH2_Appl_Layer/Pic_etat_monitor.Reset
         break;
      }
      case Cb46_greenState_id: {
         // Begin execution of state BVH2_Appl_Layer/Pic_etat_monitor.greenState
         Cb44_Pic_etat_monitor_node_fcn1();
         if (SIBFS_Pic_etat_monitor_b.Cb44_glflag <= 2) {
            Cb44_StateCnt = Cb44_StateCnt + 1;
         }

         // End execution of state BVH2_Appl_Layer/Pic_etat_monitor.greenState
         break;
      }
      case Cb47_Alarm_Off_id: {
         // Begin execution of state BVH2_Appl_Layer/Pic_etat_monitor.Alarm_Off
         Cb44_Pic_etat_monitor_node_fcn1();

         // End execution of state BVH2_Appl_Layer/Pic_etat_monitor.Alarm_Off
         break;
      }
      case Cb48_Wait_id: {
         // Begin execution of state BVH2_Appl_Layer/Pic_etat_monitor.Wait
         if (Cb44_StateCnt > 15) {
            // State transition to BVH2_Appl_Layer/Pic_etat_monitor.greenState
            SIBFS_Pic_etat_monitor_b.Cb44_Pic_etat_monitor_ns = (unsigned int) Cb46_greenState_id;
            Cb44_oShutoff = 0;
            Cb44_oAlarm = 0;
            Cb44_StateCnt = 0;
         }
         else {
            // BVH2_Appl_Layer/Pic_etat_monitor: Omitted comparison with constant.
            //   # combined # update of inport for BVH2_Appl_Layer/Pic_etat_monitor
            if (bool_mat_pic_etat) {
               // State transition to BVH2_Appl_Layer/Pic_etat_monitor.redState
               SIBFS_Pic_etat_monitor_b.Cb44_Pic_etat_monitor_ns = (unsigned int) Cb50_redState_id;
               Cb44_StateCnt = 0;
               Cb44_oShutoff = 1;
               Cb44_oAlarm = 1;
            }
            else {
               Cb44_StateCnt = Cb44_StateCnt + 1;
            }
         }

         // End execution of state BVH2_Appl_Layer/Pic_etat_monitor.Wait
         break;
      }
      case Cb49_Wrong_ETAT_id: {
         // Begin execution of state BVH2_Appl_Layer/Pic_etat_monitor.Wrong_ETAT

         // BVH2_Appl_Layer/Pic_etat_monitor: Omitted comparison with constant.
         //   # combined # update of inport for BVH2_Appl_Layer/Pic_etat_monitor
         if (!(bool_mat_pic_etat)) {
            // State transition to BVH2_Appl_Layer/Pic_etat_monitor.Alarm_Off
            SIBFS_Pic_etat_monitor_b.Cb44_Pic_etat_monitor_ns = (unsigned int) Cb47_Alarm_Off_id;
            Cb44_oShutoff = 0;
            Cb44_oAlarm = 0;
         }
         else {
            if (Cb44_StateCnt) {
               // State transition to BVH2_Appl_Layer/Pic_etat_monitor.redState
               SIBFS_Pic_etat_monitor_b.Cb44_Pic_etat_monitor_ns = (unsigned int) Cb50_redState_id;
               Cb44_StateCnt = 0;
               Cb44_oShutoff = 1;
               Cb44_oAlarm = 1;
            }
            else {
               Cb44_StateCnt = Cb44_StateCnt + 1;
            }
         }

         // End execution of state BVH2_Appl_Layer/Pic_etat_monitor.Wrong_ETAT
         break;
      }
      case Cb50_redState_id: {
         // Begin execution of state BVH2_Appl_Layer/Pic_etat_monitor.redState

         // BVH2_Appl_Layer/Pic_etat_monitor: Omitted comparison with constant.
         //   # combined # update of inport for BVH2_Appl_Layer/Pic_etat_monitor
         if (!(bool_mat_pic_etat)) {
            // State transition from BVH2_Appl_Layer/Pic_etat_monitor.redState to BVH2_Appl_Layer/Pi
            //   c_etat_monitor.Wait
            SIBFS_Pic_etat_monitor_b.Cb44_Pic_etat_monitor_ns = (unsigned int) Cb48_Wait_id;
            Cb44_StateCnt = 0;
         }

         // End execution of state BVH2_Appl_Layer/Pic_etat_monitor.redState
         break;
      }
      default: {
         // BVH2_Appl_Layer/Pic_etat_monitor: Omitted comparison with constant.
         if (!(SIBFS_Pic_etat_monitor_b.Cb44_Pic_etat_monitor)) {
            SIBFS_Pic_etat_monitor_b.Cb44_Pic_etat_monitor = 1;

            // BVH2_Appl_Layer/Pic_etat_monitor: Omitted comparison with constant.
            //   # combined # update of inport for BVH2_Appl_Layer/Pic_etat_monitor
            if (ui8_ResetMatlab != 0) {
               // State transition to BVH2_Appl_Layer/Pic_etat_monitor.Reset
               SIBFS_Pic_etat_monitor_b.Cb44_Pic_etat_monitor_ns = (unsigned int) Cb45_Reset_id;
               Cb44_StateCnt = 0;
            }
         }
      }
   }

   // End execution of chart BVH2_Appl_Layer/Pic_etat_monitor

   // Outport: BVH2_Appl_Layer/PICalarm
   bool_PIC_Alarm = Cb44_oAlarm;

   // update of inport for BVH2_Appl_Layer/PWM_Detection
   //Cb34_idPWM = ui8_PWM_dc_mat;
   Cb34_idPWM = 50;  // faking this out in order to bypass alarms

   // Begin execution of chart BVH2_Appl_Layer/PWM_Detection

   // BVH2_Appl_Layer/PWM_Detection: Omitted comparison with constant.
   if (SIBFS_PWM_Detection_b.Cb35_PWMinput_handling) {
      /* Begin execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling */
      switch (SIBFS_PWM_Detection_b.Cb35_PWMinput_handling_ns) {
         case Cb36_LimpModeLow_id: {
            /* Begin execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.LimpModeLow
             */
            Cb34_PWM_Detection_node_fcn1();

            /* End execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.LimpModeLow */
            break;
         }
         case Cb37_LimpModeLow1_id: {
            /* Begin execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.LimpModeLow1
             */
            Cb34_PWM_Detection_node_fcn1();

            /* End execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.LimpModeLow1
             */
            break;
         }
         case Cb38_SaturationHigh_id: {
            /* Begin execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.SaturationHi
               gh */
            Cb34_PWM_Detection_node_fcn1();

            /* End execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.SaturationHigh
             */
            break;
         }
         case Cb39_Alarm_id: {
            /* Begin execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.Alarm */
            Cb34_PWM_Detection_node_fcn1();

            /* End execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.Alarm */
            break;
         }
         case Cb40_CMD_MJP_0_100_id: {
            /* Begin execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.CMD_MJP_0_10
               0 */
            Cb34_PWM_Detection_node_fcn1();

            /* End execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.CMD_MJP_0_100
             */
            break;
         }
         case Cb41_Normal3_id: {
            /* Begin execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.Normal3 */
            Cb34_PWM_Detection_node_fcn1();

            /* End execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.Normal3 */
            break;
         }
         case Cb42_SaturationLow_id: {
            /* Begin execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.SaturationLo
               w */
            Cb34_PWM_Detection_node_fcn1();

            /* End execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.SaturationLow
             */
            break;
         }
         case Cb43_PumpOff2_id: {
            /* Begin execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.PumpOff2 */
            Cb34_PWM_Detection_node_fcn1();

            /* End execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.PumpOff2 */
            break;
         }
      }

      /* End execution of state BVH2_Appl_Layer/PWM_Detection.PWMinput_handling */
   }
   else {
      SIBFS_PWM_Detection_b.Cb35_PWMinput_handling = 1;

      /* # combined # update of inport for BVH2_Appl_Layer/PWM_Detection */
      if (ui8_ResetMatlab == 1) {
         /* State transition to BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.PumpOff2 */
         SIBFS_PWM_Detection_b.Cb35_PWMinput_handling_ns = (unsigned int) Cb43_PumpOff2_id;
         Cb34_odPumpOff = 1;
         Cb34_odFixedValueSel = 0;
         Cb34_odFixedLowValueSel = 0;
         Cb34_oPWM_SC_Alarm = 0;
         Cb34_oPWM_Alarm = 0;
      }
   }

   /* End execution of chart BVH2_Appl_Layer/PWM_Detection */

   /* Outport: BVH2_Appl_Layer/PWMin_Freq_Alarm */
   bool_PWMin_Freq_err_Alarm = Cb34_oPWM_SC_Alarm;

   /* Begin execution of chart BVH2_Appl_Layer/UbatHandling */

   /* BVH2_Appl_Layer/UbatHandling: Omitted comparison with constant. */
   if (SIBFS_UbatHandling_b.Cb57_Ubat_Handling) {
      /* Begin execution of state BVH2_Appl_Layer/UbatHandling.Ubat_Handling */

      /* BVH2_Appl_Layer/UbatHandling: Omitted comparison with constant. */
      if (SIBFS_UbatHandling_b.Cb58_SaturationHigh) {
         /* Begin execution of state BVH2_Appl_Layer/UbatHandling.Ubat_Handling.SaturationHigh */
         SIBFS_UbatHandling_b.Aux_sflag3 = 2 /* 2. */;

         /* # combined # update of inport for BVH2_Appl_Layer/UbatHandling */
         if (((UInt8)ui8_BattVolt_mat) < 139) { /*was 222 */
            Cb56_UbatHandling_node_fcn2();
         }

         /* End execution of state BVH2_Appl_Layer/UbatHandling.Ubat_Handling.SaturationHigh */
      }
      else {
         /* BVH2_Appl_Layer/UbatHandling: Omitted comparison with constant. */
         if (SIBFS_UbatHandling_b.Cb59_SaturationLow) {
            /* Begin execution of state BVH2_Appl_Layer/UbatHandling.Ubat_Handling.SaturationLow */
            SIBFS_UbatHandling_b.Aux_sflag3 = 3 /* 3. */;

            /* # combined # update of inport for BVH2_Appl_Layer/UbatHandling */
            if (((UInt8)ui8_BattVolt_mat) > 49) {
               Cb56_UbatHandling_node_fcn2();
            }

            /* End execution of state BVH2_Appl_Layer/UbatHandling.Ubat_Handling.SaturationLow */
         }
         else {
            /* BVH2_Appl_Layer/UbatHandling: Omitted comparison with constant. */
            if (SIBFS_UbatHandling_b.Cb60_NormalUbat) {
               /* Begin execution of state BVH2_Appl_Layer/UbatHandling.Ubat_Handling.NormalUbat */
               SIBFS_UbatHandling_b.Aux_sflag3 = 1 /* 1. */;
               Cb56_UbatHandling_node_fcn2();

               /* End execution of state BVH2_Appl_Layer/UbatHandling.Ubat_Handling.NormalUbat */
            }
         }
      }

      /* End execution of state BVH2_Appl_Layer/UbatHandling.Ubat_Handling */
   }
   else {
      SIBFS_UbatHandling_b.Cb57_Ubat_Handling = 1;

      /* # combined # update of inport for BVH2_Appl_Layer/UbatHandling */
      if (ui8_ResetMatlab == 1) {
         /* State transition to BVH2_Appl_Layer/UbatHandling.Ubat_Handling.NormalUbat */
         SIBFS_UbatHandling_b.Cb60_NormalUbat = 1;
         Cb56_odPumpOff = 0;
         Cb56_odFixedValueSel = 0;
         Cb56_oUbat_Alarm_High = 0;
      }
   }

   /* End execution of chart BVH2_Appl_Layer/UbatHandling */
   Sb1_Logical_Operator2 = 0;//2Cb34_odPumpOff && (!(Cb56_odFixedValueSel));

   /* Begin execution of chart BVH2_Appl_Layer/Temperature_Alarm */

   /* BVH2_Appl_Layer/Temperature_Alarm: Omitted comparison with constant. */
   if (SIBFS_Temperature_Alarm_b.Cb52_CntOverTemp) {
      /* Begin execution of state BVH2_Appl_Layer/Temperature_Alarm.CntOverTemp */
      if (Cb51_Counter > 80) {
         /* State transition from BVH2_Appl_Layer/Temperature_Alarm.CntOverTemp to BVH2_Appl_Layer/T
            emperature_Alarm.greenTemp */
         SIBFS_Temperature_Alarm_b.Cb52_CntOverTemp = 0;
         SIBFS_Temperature_Alarm_b.Cb54_greenTemp = 1;
         Cb51_oTempRedAlarm = 0;
         Cb51_oTempAlarm = 0;
         Cb51_odPumpOff = 0;
         Cb51_Counter = 0 /* 0. */;
      }
      else {
         Cb51_Counter = Cb51_Counter + 1 /* 1. */;
      }

      /* End execution of state BVH2_Appl_Layer/Temperature_Alarm.CntOverTemp */
   }
   else {
      /* BVH2_Appl_Layer/Temperature_Alarm: Omitted comparison with constant. */
      if (SIBFS_Temperature_Alarm_b.Cb53_reset) {
         /* Begin execution of state BVH2_Appl_Layer/Temperature_Alarm.reset */

         /* State transition from BVH2_Appl_Layer/Temperature_Alarm.reset to BVH2_Appl_Layer/Tempera
            ture_Alarm.CntOverTemp */
         SIBFS_Temperature_Alarm_b.Cb53_reset = 0;
         SIBFS_Temperature_Alarm_b.Cb52_CntOverTemp = 1;

         /* End execution of state BVH2_Appl_Layer/Temperature_Alarm.reset */
      }
      else {
         /* BVH2_Appl_Layer/Temperature_Alarm: Omitted comparison with constant. */
         if (SIBFS_Temperature_Alarm_b.Cb54_greenTemp) {
            /* Begin execution of state BVH2_Appl_Layer/Temperature_Alarm.greenTemp */

            /* # combined # update of inport for BVH2_Appl_Layer/Temperature_Alarm */
            if (ui16_mat_inpTemp < 72) {
               /* State transition from BVH2_Appl_Layer/Temperature_Alarm.greenTemp to BVH2_Appl_Lay
                  er/Temperature_Alarm.redTemp */
               SIBFS_Temperature_Alarm_b.Cb54_greenTemp = 0;
               SIBFS_Temperature_Alarm_b.Cb55_redTemp = 1;
               Cb51_oTempRedAlarm = 1;
               Cb51_oTempAlarm = 1;

               /* test */
               Cb51_odPumpOff = 0;
            }

            /* End execution of state BVH2_Appl_Layer/Temperature_Alarm.greenTemp */
         }
         else {
            /* BVH2_Appl_Layer/Temperature_Alarm: Omitted comparison with constant. */
            if (SIBFS_Temperature_Alarm_b.Cb55_redTemp) {
               /* Begin execution of state BVH2_Appl_Layer/Temperature_Alarm.redTemp */

               /* # combined # update of inport for BVH2_Appl_Layer/Temperature_Alarm */
               if (ui16_mat_inpTemp > 185) {
                  /* State transition from BVH2_Appl_Layer/Temperature_Alarm.redTemp to BVH2_Appl_La
                     yer/Temperature_Alarm.greenTemp */
                  SIBFS_Temperature_Alarm_b.Cb55_redTemp = 0;
                  SIBFS_Temperature_Alarm_b.Cb54_greenTemp = 1;
                  Cb51_oTempRedAlarm = 0;
                  Cb51_oTempAlarm = 0;
                  Cb51_odPumpOff = 0;
                  Cb51_Counter = 0 /* 0. */;
               }

               /* End execution of state BVH2_Appl_Layer/Temperature_Alarm.redTemp */
            }
            else {
               /* BVH2_Appl_Layer/Temperature_Alarm: Omitted comparison with constant. */
               if (!(SIBFS_Temperature_Alarm_b.Cb51_Temperature_Alarm)) {
                  SIBFS_Temperature_Alarm_b.Cb51_Temperature_Alarm = 1;

                  /* BVH2_Appl_Layer/Temperature_Alarm: Omitted comparison with constant.
                     # combined # update of inport for BVH2_Appl_Layer/Temperature_Alarm */
                  if (ui8_ResetMatlab != 0) {
                     /* State transition to BVH2_Appl_Layer/Temperature_Alarm.reset */
                     SIBFS_Temperature_Alarm_b.Cb53_reset = 1;
                     Cb51_Counter = 0 /* 0. */;
                  }
               }
            }
         }
      }
   }

   /* End execution of chart BVH2_Appl_Layer/Temperature_Alarm */

   /* Begin execution of chart BVH2_Appl_Layer/Current_Analysis_High */
   switch (SIBFS_Current_Analysis_High_b.Cb1_Current_Analysis_High_ns) {
      case Cb2_Reset_id: {
         /* Begin execution of state BVH2_Appl_Layer/Current_Analysis_High.Reset */
         if (Cb1_StateCnt > 50) {
            /* State transition from BVH2_Appl_Layer/Current_Analysis_High.Reset to BVH2_Appl_Layer/
               Current_Analysis_High.Alarm_Off */
            SIBFS_Current_Analysis_High_b.Cb1_Current_Analysis_High_ns = (unsigned int)
             Cb5_Alarm_Off_id;
            Cb1_oShutoff = 0;
            Cb1_oCurrentAlarm = 0;
            Cb1_RestartCounter = 0 /* 0. */;
         }
         else {
            Cb1_StateCnt = Cb1_StateCnt + 1 /* 1. */;
         }

         /* End execution of state BVH2_Appl_Layer/Current_Analysis_High.Reset */
         break;
      }
      case Cb3_greenState_id: {
         /* Begin execution of state BVH2_Appl_Layer/Current_Analysis_High.greenState */
         Cb1_Current_An___High_node_fcn1();
         if (SIBFS_Current_Analysis_High_b.Cb1_glflag <= 2) {
            Cb1_StateCnt = Cb1_StateCnt + 1 /* 1. */;
         }

         /* End execution of state BVH2_Appl_Layer/Current_Analysis_High.greenState */
         break;
      }
      case Cb4_RestartCounter_id: {
         /* Begin execution of state BVH2_Appl_Layer/Current_Analysis_High.RestartCounter */
         if (Cb1_RestartCounter < 10) {
            /* State transition from BVH2_Appl_Layer/Current_Analysis_High.RestartCounter to BVH2_Ap
               pl_Layer/Current_Analysis_High.greenState */
            SIBFS_Current_Analysis_High_b.Cb1_Current_Analysis_High_ns = (unsigned int)
             Cb3_greenState_id;
            Cb1_oShutoff = 0;
            Cb1_oCurrentAlarm = 1;
            Cb1_StateCnt = 0 /* 0. */;
         }

         /* End execution of state BVH2_Appl_Layer/Current_Analysis_High.RestartCounter */
         break;
      }
      case Cb5_Alarm_Off_id: {
         /* Begin execution of state BVH2_Appl_Layer/Current_Analysis_High.Alarm_Off */
         Cb1_Current_An___High_node_fcn1();

         /* End execution of state BVH2_Appl_Layer/Current_Analysis_High.Alarm_Off */
         break;
      }
      case Cb6_Wait_id: {
         /* Begin execution of state BVH2_Appl_Layer/Current_Analysis_High.Wait */
         if (Cb1_StateCnt > 200) {
            /* State transition to BVH2_Appl_Layer/Current_Analysis_High.RestartCounter */
            SIBFS_Current_Analysis_High_b.Cb1_Current_Analysis_High_ns = (unsigned int)
             Cb4_RestartCounter_id;
            Cb1_RestartCounter = Cb1_RestartCounter + 1 /* 1. */;
         }
         else {
            /* BVH2_Appl_Layer/Current_Analysis_High: Omitted comparison with constant.
               # combined # update of inport for BVH2_Appl_Layer/Current_Analysis_High */
            if (bool_mat_currAlarm_bldc) {
               /* State transition to BVH2_Appl_Layer/Current_Analysis_High.redState */
               SIBFS_Current_Analysis_High_b.Cb1_Current_Analysis_High_ns = (unsigned int)
                Cb8_redState_id;
               Cb1_StateCnt = 0 /* 0. */;
               //Cb1_oShutoff = 1;
               Cb1_oCurrentAlarm = 1;
            }
            else {
               Cb1_StateCnt = Cb1_StateCnt + 1 /* 1. */;
            }
         }

         /* End execution of state BVH2_Appl_Layer/Current_Analysis_High.Wait */
         break;
      }
      case Cb7_CntOverCurrent_id: {
         /* Begin execution of state BVH2_Appl_Layer/Current_Analysis_High.CntOverCurrent */

         /* BVH2_Appl_Layer/Current_Analysis_High: Omitted comparison with constant.
            # combined # update of inport for BVH2_Appl_Layer/Current_Analysis_High */
         if (!(bool_mat_currAlarm_bldc)) {
            /* State transition to BVH2_Appl_Layer/Current_Analysis_High.greenState */
            SIBFS_Current_Analysis_High_b.Cb1_Current_Analysis_High_ns = (unsigned int)
             Cb3_greenState_id;
            Cb1_oShutoff = 0;
            Cb1_oCurrentAlarm = 1;
            Cb1_StateCnt = 0 /* 0. */;
         }
         else {
            if (Cb1_StateCnt > 1) {
               /* State transition to BVH2_Appl_Layer/Current_Analysis_High.redState */
               SIBFS_Current_Analysis_High_b.Cb1_Current_Analysis_High_ns = (unsigned int)
                Cb8_redState_id;
               Cb1_StateCnt = 0 /* 0. */;
               //Cb1_oShutoff = 1;
               Cb1_oCurrentAlarm = 1;
            }
            else {
               Cb1_StateCnt = Cb1_StateCnt + 1 /* 1. */;
            }
         }

         /* End execution of state BVH2_Appl_Layer/Current_Analysis_High.CntOverCurrent */
         break;
      }
      case Cb8_redState_id: {
         /* Begin execution of state BVH2_Appl_Layer/Current_Analysis_High.redState */

         /* BVH2_Appl_Layer/Current_Analysis_High: Omitted comparison with constant.
            # combined # update of inport for BVH2_Appl_Layer/Current_Analysis_High */
         if (!(bool_mat_currAlarm_bldc)) {
            /* State transition from BVH2_Appl_Layer/Current_Analysis_High.redState to BVH2_Appl_Lay
               er/Current_Analysis_High.Wait */
            SIBFS_Current_Analysis_High_b.Cb1_Current_Analysis_High_ns = (unsigned int) Cb6_Wait_id;
            Cb1_StateCnt = 0 /* 0. */;
         }
         else {
            Cb1_StateCnt = Cb1_StateCnt + 1 /* 1. */;
         }

         /* End execution of state BVH2_Appl_Layer/Current_Analysis_High.redState */
         break;
      }
      default: {
         /* BVH2_Appl_Layer/Current_Analysis_High: Omitted comparison with constant. */
         if (!(SIBFS_Current_Analysis_High_b.Cb1_Current_Analysis_High)) {
            SIBFS_Current_Analysis_High_b.Cb1_Current_Analysis_High = 1;

            /* BVH2_Appl_Layer/Current_Analysis_High: Omitted comparison with constant.
               # combined # update of inport for BVH2_Appl_Layer/Current_Analysis_High */
            if (ui8_ResetMatlab != 0) {
               /* State transition to BVH2_Appl_Layer/Current_Analysis_High.Reset */
               SIBFS_Current_Analysis_High_b.Cb1_Current_Analysis_High_ns = (unsigned int)
                Cb2_Reset_id;
               Cb1_StateCnt = 0 /* 0. */;
               Cb1_RestartCounter = 0 /* 0. */;
            }
         }
      }
   }

   /* End execution of chart BVH2_Appl_Layer/Current_Analysis_High */
   Sb1_Logical_Operator1 = Sb1_Logical_Operator2 || Cb56_odPumpOff || Cb51_odPumpOff ||
    Cb1_oShutoff || Cb44_oShutoff;

   /* update of inport for BVH2_Appl_Layer/Motor_Stalled */
   Cb24_Reset = ui8_ResetMatlab != 0 /* 0. */;

   /* Begin execution of chart BVH2_Appl_Layer/Motor_Stalled */

   /* BVH2_Appl_Layer/Motor_Stalled: Omitted comparison with constant. */
   if (SIBFS_Motor_Stalled_b.Cb25_Motor_stalled_Statemachine) {
      /* Begin execution of state BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine */

      /* BVH2_Appl_Layer/Motor_Stalled: Omitted comparison with constant.
         BVH2_Appl_Layer/Motor_Stalled: Omitted comparison with constant.
         # combined # update of inport for BVH2_Appl_Layer/Motor_Stalled */
      if (Sb1_Logical_Operator1 || Cb24_Reset) {
         /* State transition from BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine to BVH2_A
            ppl_Layer/Motor_Stalled.default */
         switch (SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns) {
            case Cb26_CntStart_id: {
               Cb24_StateCnt = 0 /* 0. */;
               SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = 0 /* 0. */;
               break;
            }
            case Cb27_Speed_detection_id: {
               SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = 0 /* 0. */;
               break;
            }
            case Cb28_SpeedBad_cnt_id: {
               SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = 0 /* 0. */;
               break;
            }
            case Cb29_Motor_Run_id: {
               SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = 0 /* 0. */;
               break;
            }
            case Cb30_Motor_Wait_id: {
               SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = 0 /* 0. */;
               break;
            }
            case Cb31_Motor_Stalled_id: {
               SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = 0 /* 0. */;
               break;
            }
         }
         SIBFS_Motor_Stalled_b.Cb25_Motor_stalled_Statemachine = 0;
         SIBFS_Motor_Stalled_b.Cb32_default = 1;
         Cb24_oMotorStalled = 0;
         Cb24_oStalledAlarm = 0;
         Cb24_RestartCounter = 0 /* 0. */;
      }
      else {
         switch (SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns) {
            case Cb26_CntStart_id: {
               /* Begin execution of state BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.
                  CntStart */
               if (Cb24_StateCnt) {
                  /* State transition from BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.
                     CntStart to BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.Speed_dete
                     ction */
                  Cb24_StateCnt = 0 /* 0. */;
                  SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = (unsigned int)
                   Cb27_Speed_detection_id;
               }
               else {
                  Cb24_StateCnt = Cb24_StateCnt + 1 /* 1. */;
               }

               /* End execution of state BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.Cn
                  tStart */
               break;
            }
            case Cb27_Speed_detection_id: {
               /* Begin execution of state BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.
                  Speed_detection */
               if (Cb24_StateCnt > 1000) {
                  /* State transition to BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.Mo
                     tor_Run */
                  SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = (unsigned int)
                   Cb29_Motor_Run_id;
                  Cb24_StateCnt = 0 /* 0. */;
                  Cb24_BadCnt = 0 /* 0. */;
                  Cb24_oMotorStalled = 0;

                  /* Detection allways */
                  Cb24_oStalledAlarm = 0;
               }
               else {
                  /* # combined # update of inport for BVH2_Appl_Layer/Motor_Stalled
                     # combined # update of inport for BVH2_Appl_Layer/Motor_Stalled */
                  if ((ui16_Speed_mat < 5) || (ui16_Speed_mat > 300)) {
                     /* State transition to BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine
                        .SpeedBad_cnt */
                     SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = (unsigned int)
                      Cb28_SpeedBad_cnt_id;
                     Cb24_oStalledAlarm = 0;
                     Cb24_StateCnt = 0 /* 0. */;
                  }
                  else {
                     Cb24_StateCnt = Cb24_StateCnt + 1 /* 1. */;
                  }
               }

               /* End execution of state BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.Sp
                  eed_detection */
               break;
            }
            case Cb28_SpeedBad_cnt_id: {
               /* Begin execution of state BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.
                  SpeedBad_cnt */
               if (Cb24_BadCnt > 100) {
                  /* State transition to BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.Mo
                     tor_Stalled */
                  SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = (unsigned int)
                   Cb31_Motor_Stalled_id;
                  Cb24_StateCnt = 0 /* 0. */;
                  Cb24_oMotorStalled = 1;
                  Cb24_oStalledAlarm = 1;
               }
               else {
                  /* # combined # update of inport for BVH2_Appl_Layer/Motor_Stalled
                     # combined # update of inport for BVH2_Appl_Layer/Motor_Stalled */
                  if ((ui16_Speed_mat >= 5) && (ui16_Speed_mat <= 300)) {
                     /* State transition to BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine
                        .Speed_detection */
                     SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = (unsigned int)
                      Cb27_Speed_detection_id;
                  }
                  else {
                     Cb24_BadCnt = Cb24_BadCnt + 1 /* 1. */;
                     Cb24_StateCnt = Cb24_StateCnt + 1 /* 1. */;
                  }
               }

               /* End execution of state BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.Sp
                  eedBad_cnt */
               break;
            }
            case Cb29_Motor_Run_id: {
               /* Begin execution of state BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.
                  Motor_Run */

               /* State transition from BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.Mot
                  or_Run to BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.Speed_detection
                */
               SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = (unsigned int)
                Cb27_Speed_detection_id;

               /* End execution of state BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.Mo
                  tor_Run */
               break;
            }
            case Cb30_Motor_Wait_id: {
               /* Begin execution of state BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.
                  Motor_Wait */
               if (Cb24_StateCnt > 10) {
                  if (Cb24_RestartCounter == 10) {
                     /* State transition to BVH2_Appl_Layer/Motor_Stalled.Stop */
                     SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = 0 /* 0. */;
                     SIBFS_Motor_Stalled_b.Cb25_Motor_stalled_Statemachine = 0;
                     SIBFS_Motor_Stalled_b.Cb33_Stop = 1;
                     Cb24_oStalledAlarm = 1;
                     Cb24_oMotorStalled = 1;
                     SIBFS_Motor_Stalled_b.Cb24_glflag = 3 /* 3. */;
                  }
                  else {
                     /* # combined # update of inport for BVH2_Appl_Layer/Motor_Stalled
                        # combined # update of inport for BVH2_Appl_Layer/Motor_Stalled */
                     if ((ui16_Speed_mat < 5) || (ui16_Speed_mat > 300)) {
                        /* State transition to BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemach
                           ine.Motor_Stalled */
                        SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = (unsigned int)
                         Cb31_Motor_Stalled_id;
                        Cb24_StateCnt = 0 /* 0. */;
                        Cb24_oMotorStalled = 1;
                        Cb24_oStalledAlarm = 1;
                        SIBFS_Motor_Stalled_b.Cb24_glflag = 3 /* 3. */;
                     }
                     else {
                        if (Cb24_StateCnt > 200) {
                           /* State transition to BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statem
                              achine.Motor_Run */
                           SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = (unsigned int)
                            Cb29_Motor_Run_id;
                           Cb24_StateCnt = 0 /* 0. */;
                           Cb24_BadCnt = 0 /* 0. */;
                           Cb24_oMotorStalled = 0;

                           /* Detection allways */
                           Cb24_oStalledAlarm = 0;
                           SIBFS_Motor_Stalled_b.Cb24_glflag = 3 /* 3. */;
                        }
                        else {
                           SIBFS_Motor_Stalled_b.Cb24_glflag = 1 /* 1. */;
                        }
                     }
                  }
               }
               else {
                  SIBFS_Motor_Stalled_b.Cb24_glflag = 0 /* 0. */;
               }
               if (SIBFS_Motor_Stalled_b.Cb24_glflag <= 2) {
                  Cb24_StateCnt = Cb24_StateCnt + 1 /* 1. */;
               }

               /* End execution of state BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.Mo
                  tor_Wait */
               break;
            }
            case Cb31_Motor_Stalled_id: {
               /* Begin execution of state BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.
                  Motor_Stalled */
               if (Cb24_StateCnt > 200) {
                  /* State transition from BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.
                     Motor_Stalled to BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.Motor
                     _Wait */
                  SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = (unsigned int)
                   Cb30_Motor_Wait_id;
                  Cb24_StateCnt = 0 /* 0. */;
                  Cb24_oMotorStalled = 0;
                  Cb24_oStalledAlarm = 1;
                  Cb24_RestartCounter = Cb24_RestartCounter + 1 /* 1. */;
               }
               else {
                  Cb24_StateCnt = Cb24_StateCnt + 1 /* 1. */;
               }

               /* End execution of state BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine.Mo
                  tor_Stalled */
               break;
            }
         }
      }

      /* End execution of state BVH2_Appl_Layer/Motor_Stalled.Motor_stalled_Statemachine */
   }
   else {
      /* BVH2_Appl_Layer/Motor_Stalled: Omitted comparison with constant. */
      if (SIBFS_Motor_Stalled_b.Cb32_default) {
         /* Begin execution of state BVH2_Appl_Layer/Motor_Stalled.default */

         /* BVH2_Appl_Layer/Motor_Stalled: Omitted comparison with constant.
            # combined # update of inport for BVH2_Appl_Layer/Motor_Stalled */
         if (!(Sb1_Logical_Operator1)) {
            /* State transition from BVH2_Appl_Layer/Motor_Stalled.default to BVH2_Appl_Layer/Motor_
               Stalled.Motor_stalled_Statemachine.CntStart */
            SIBFS_Motor_Stalled_b.Cb32_default = 0;
            SIBFS_Motor_Stalled_b.Cb25_Motor_stalled_Statemachine = 1;
            SIBFS_Motor_Stalled_b.Cb25_Motor_sta__Statemachine_ns = (unsigned int) Cb26_CntStart_id;
            Cb24_StateCnt = 0 /* 0. */;
            Cb24_BadCnt = 0 /* 0. */;
         }

         /* End execution of state BVH2_Appl_Layer/Motor_Stalled.default */
      }
      else {
         /* BVH2_Appl_Layer/Motor_Stalled: Omitted comparison with constant. */
         if (!(SIBFS_Motor_Stalled_b.Cb33_Stop)) {
            /* BVH2_Appl_Layer/Motor_Stalled: Omitted comparison with constant. */
            if (!(SIBFS_Motor_Stalled_b.Cb24_Motor_Stalled)) {
               SIBFS_Motor_Stalled_b.Cb24_Motor_Stalled = 1;

               /* BVH2_Appl_Layer/Motor_Stalled: Omitted comparison with constant. */
               if (Cb24_Reset) {
                  /* State transition to BVH2_Appl_Layer/Motor_Stalled.default */
                  SIBFS_Motor_Stalled_b.Cb32_default = 1;
                  Cb24_oMotorStalled = 0;
                  Cb24_oStalledAlarm = 0;
                  Cb24_RestartCounter = 0 /* 0. */;
               }
            }
         }
      }
   }

   /* End execution of chart BVH2_Appl_Layer/Motor_Stalled */

   /* Outport: BVH2_Appl_Layer/StalledMotorStop */
   bool_StalledMotorStop = Cb24_oMotorStalled;
   Sb1_Logical_Operator5 = Cb34_odFixedValueSel || Cb56_odFixedValueSel;

   /* SwitchBVH2_Appl_Layer/Controller/Switch5
      BVH2_Appl_Layer/Controller/Switch5: Omitted comparison with constant. */
   if (bool_start_demand_mat) {
      Sb2_Switch5 = ui8_fixed_start_speed_mat;
   }
   else {
      /* SwitchBVH2_Appl_Layer/Controller/Switch4
         BVH2_Appl_Layer/Controller/Switch4: Omitted comparison with constant. */
      if (Cb34_odFixedLowValueSel) {
         Sb2_Switch5 = ui16_Speed_demand_mat_min;
      }
      else {
         /* SwitchBVH2_Appl_Layer/Controller/Switch3
            BVH2_Appl_Layer/Controller/Switch3: Omitted comparison with constant. */
         if (Sb1_Logical_Operator5) {
            Sb2_Switch5 = ui16_Speed_demand_mat_Max;
         }
         else {
            Sb2_Switch5 = ui16_Speed_demand_mat;
         }
      }
   }

   /* Sum: BVH2_Appl_Layer/Controller/Error */
   Sb2_Error = (Int16) (ui16_Speed_mat - Sb2_Switch5);

   /* Begin execution of chart BVH2_Appl_Layer/Dry_Running */

   /* BVH2_Appl_Layer/Dry_Running: Omitted comparison with constant. */
   if (SIBFS_Dry_Running_b.Cb15_greenState) {
      /* Begin execution of state BVH2_Appl_Layer/Dry_Running.greenState */

      /* # combined # update of inport for BVH2_Appl_Layer/Dry_Running
         # combined # update of inport for BVH2_Appl_Layer/Dry_Running
         # combined # update of inport for BVH2_Appl_Layer/Dry_Running
         # combined # update of inport for BVH2_Appl_Layer/Dry_Running */
      if ((((Int32)ui16_mat_Current) < (ui16_dryRun_Thresh - 5)) && (ui16_Speed_mat < 400) &&
       (ui16_Speed_mat > 80)) {
         /* State transition from BVH2_Appl_Layer/Dry_Running.greenState to BVH2_Appl_Layer/Dry_Runn
            ing.DryRunning.CntOverCurrent */
         //SIBFS_Dry_Running_b.Cb15_greenState = 0;
         //SIBFS_Dry_Running_b.Cb16_DryRunning = 1;
         //SIBFS_Dry_Running_b.Cb18_CntOverCurrent = 1;
         //Cb14_StateCnt = 0 /* 0. */;
         //Cb14_oDryRunAlarm = 0;
      }

      /* End execution of state BVH2_Appl_Layer/Dry_Running.greenState */
   }
   else {
      /* BVH2_Appl_Layer/Dry_Running: Omitted comparison with constant. */
      if (SIBFS_Dry_Running_b.Cb16_DryRunning) {
         /* Begin execution of state BVH2_Appl_Layer/Dry_Running.DryRunning */

         /* BVH2_Appl_Layer/Dry_Running: Omitted comparison with constant. */
         if (!(SIBFS_Dry_Running_b.Cb17_redState)) {
            /* BVH2_Appl_Layer/Dry_Running: Omitted comparison with constant. */
            if (SIBFS_Dry_Running_b.Cb18_CntOverCurrent) {
               /* Begin execution of state BVH2_Appl_Layer/Dry_Running.DryRunning.CntOverCurrent */

               /* # combined # update of inport for BVH2_Appl_Layer/Dry_Running
                  # combined # update of inport for BVH2_Appl_Layer/Dry_Running
                  # combined # update of inport for BVH2_Appl_Layer/Dry_Running
                  # combined # update of inport for BVH2_Appl_Layer/Dry_Running */
                if ((((UInt32)ui16_mat_Current) > (ui16_dryRun_Thresh + 5)) || (ui16_Speed_mat >
                400) || (ui16_Speed_mat < 80)) {
                  /* State transition to BVH2_Appl_Layer/Dry_Running.greenState */
                  SIBFS_Dry_Running_b.Cb18_CntOverCurrent = 0;
                  SIBFS_Dry_Running_b.Cb16_DryRunning = 0;
                  SIBFS_Dry_Running_b.Cb15_greenState = 1;
                  Cb14_oDryRunAlarm = 0;
               }
               else {
                  if ((ui8_PWM_dc_mat < 20) && (ui8_PWM_dc_mat > 4)) {
                     /* State transition to BVH2_Appl_Layer/Dry_Running.greenState */
                     SIBFS_Dry_Running_b.Cb18_CntOverCurrent = 0;
                     SIBFS_Dry_Running_b.Cb16_DryRunning = 0;
                     SIBFS_Dry_Running_b.Cb15_greenState = 1;
                     Cb14_oDryRunAlarm = 0;
                  }
                  else {
                     if (Cb14_StateCnt > 2000) {
                        /* State transition to BVH2_Appl_Layer/Dry_Running.DryRunning.redState */
                        SIBFS_Dry_Running_b.Cb18_CntOverCurrent = 0;
                        SIBFS_Dry_Running_b.Cb17_redState = 1;
                        Cb14_oDryRunAlarm = 1;
                     }
                     else {
                        Cb14_StateCnt = Cb14_StateCnt + 1 /* 1. */;
                     }
                  }
               }

               /* End execution of state BVH2_Appl_Layer/Dry_Running.DryRunning.CntOverCurrent */
            }
         }

         /* End execution of state BVH2_Appl_Layer/Dry_Running.DryRunning */
      }
      else {
         /* BVH2_Appl_Layer/Dry_Running: Omitted comparison with constant. */
         if (!(SIBFS_Dry_Running_b.Cb14_Dry_Running)) {
            SIBFS_Dry_Running_b.Cb14_Dry_Running = 1;

            /* # combined # update of inport for BVH2_Appl_Layer/Dry_Running */
            if (ui8_ResetMatlab == 1) {
               /* State transition to BVH2_Appl_Layer/Dry_Running.greenState */
               SIBFS_Dry_Running_b.Cb15_greenState = 1;
               Cb14_oDryRunAlarm = 0;
            }
         }
      }
   }

   /* End execution of chart BVH2_Appl_Layer/Dry_Running */

   /* Begin execution of chart BVH2_Appl_Layer/Dry_RunningAlarm */

   /* BVH2_Appl_Layer/Dry_RunningAlarm: Omitted comparison with constant. */
   if (SIBFS_Dry_RunningAlarm_b.Cb20_greenState) {
      /* Begin execution of state BVH2_Appl_Layer/Dry_RunningAlarm.greenState */

      /* BVH2_Appl_Layer/Dry_RunningAlarm: Omitted comparison with constant.
         # combined # update of inport for BVH2_Appl_Layer/Dry_RunningAlarm */
      if (Cb14_oDryRunAlarm) {
         /* State transition from BVH2_Appl_Layer/Dry_RunningAlarm.greenState to BVH2_Appl_Layer/Dry
            _RunningAlarm.DryRunningAlarm.DryRun66 */
         SIBFS_Dry_RunningAlarm_b.Cb20_greenState = 0;
         SIBFS_Dry_RunningAlarm_b.Cb21_DryRunningAlarm = 1;
         SIBFS_Dry_RunningAlarm_b.Cb22_DryRun66 = 1;
         Cb19_Counter = 0 /* 0. */;
         Cb19_oDryRun66 = 1;
         Cb19_oDryRun55 = 0;
      }

      /* End execution of state BVH2_Appl_Layer/Dry_RunningAlarm.greenState */
   }
   else {
      /* BVH2_Appl_Layer/Dry_RunningAlarm: Omitted comparison with constant. */
      if (SIBFS_Dry_RunningAlarm_b.Cb21_DryRunningAlarm) {
         /* Begin execution of state BVH2_Appl_Layer/Dry_RunningAlarm.DryRunningAlarm */

         /* BVH2_Appl_Layer/Dry_RunningAlarm: Omitted comparison with constant.
            # combined # update of inport for BVH2_Appl_Layer/Dry_RunningAlarm */
         if (!(Cb14_oDryRunAlarm)) {
            /* State transition from BVH2_Appl_Layer/Dry_RunningAlarm.DryRunningAlarm to BVH2_Appl_L
               ayer/Dry_RunningAlarm.greenState */

            /* BVH2_Appl_Layer/Dry_RunningAlarm: Omitted comparison with constant. */
            if (SIBFS_Dry_RunningAlarm_b.Cb22_DryRun66) {
               SIBFS_Dry_RunningAlarm_b.Cb22_DryRun66 = 0;
            }
            else {
               /* BVH2_Appl_Layer/Dry_RunningAlarm: Omitted comparison with constant. */
               if (SIBFS_Dry_RunningAlarm_b.Cb23_DryRun55) {
                  SIBFS_Dry_RunningAlarm_b.Cb23_DryRun55 = 0;
               }
            }
            SIBFS_Dry_RunningAlarm_b.Cb21_DryRunningAlarm = 0;
            SIBFS_Dry_RunningAlarm_b.Cb20_greenState = 1;
            Cb19_oDryRun55 = 0;
            Cb19_oDryRun66 = 0;
            Cb19_Counter = 0 /* 0. */;
         }
         else {
            /* BVH2_Appl_Layer/Dry_RunningAlarm: Omitted comparison with constant. */
            if (SIBFS_Dry_RunningAlarm_b.Cb22_DryRun66) {
               /* Begin execution of state BVH2_Appl_Layer/Dry_RunningAlarm.DryRunningAlarm.DryRun66
                */
               if (Cb19_Counter > 400) {
                  /* State transition from BVH2_Appl_Layer/Dry_RunningAlarm.DryRunningAlarm.DryRun66
                      to BVH2_Appl_Layer/Dry_RunningAlarm.DryRunningAlarm.DryRun55 */
                  SIBFS_Dry_RunningAlarm_b.Cb22_DryRun66 = 0;
                  SIBFS_Dry_RunningAlarm_b.Cb23_DryRun55 = 1;
                  Cb19_Counter = 0 /* 0. */;
                  Cb19_oDryRun66 = 0;
                  Cb19_oDryRun55 = 1;
               }
               else {
                  Cb19_Counter = Cb19_Counter + 1 /* 1. */;
               }

               /* End execution of state BVH2_Appl_Layer/Dry_RunningAlarm.DryRunningAlarm.DryRun66
                */
            }
            else {
               /* BVH2_Appl_Layer/Dry_RunningAlarm: Omitted comparison with constant. */
               if (SIBFS_Dry_RunningAlarm_b.Cb23_DryRun55) {
                  /* Begin execution of state BVH2_Appl_Layer/Dry_RunningAlarm.DryRunningAlarm.DryRu
                     n55 */
                  if (Cb19_Counter > 400) {
                     /* State transition from BVH2_Appl_Layer/Dry_RunningAlarm.DryRunningAlarm.DryRu
                        n55 to BVH2_Appl_Layer/Dry_RunningAlarm.DryRunningAlarm.DryRun66 */
                     SIBFS_Dry_RunningAlarm_b.Cb23_DryRun55 = 0;
                     SIBFS_Dry_RunningAlarm_b.Cb22_DryRun66 = 1;
                     Cb19_Counter = 0 /* 0. */;
                     Cb19_oDryRun66 = 1;
                     Cb19_oDryRun55 = 0;
                  }
                  else {
                     Cb19_Counter = Cb19_Counter + 1 /* 1. */;
                  }

                  /* End execution of state BVH2_Appl_Layer/Dry_RunningAlarm.DryRunningAlarm.DryRun5
                     5 */
               }
            }
         }

         /* End execution of state BVH2_Appl_Layer/Dry_RunningAlarm.DryRunningAlarm */
      }
      else {
         /* BVH2_Appl_Layer/Dry_RunningAlarm: Omitted comparison with constant. */
         if (!(SIBFS_Dry_RunningAlarm_b.Cb19_Dry_RunningAlarm)) {
            SIBFS_Dry_RunningAlarm_b.Cb19_Dry_RunningAlarm = 1;

            /* BVH2_Appl_Layer/Dry_RunningAlarm: Omitted comparison with constant.
               # combined # update of inport for BVH2_Appl_Layer/Dry_RunningAlarm */
            if (!(Cb14_oDryRunAlarm)) {
               /* State transition to BVH2_Appl_Layer/Dry_RunningAlarm.greenState */
               SIBFS_Dry_RunningAlarm_b.Cb20_greenState = 1;
               Cb19_oDryRun55 = 0;
               Cb19_oDryRun66 = 0;
               Cb19_Counter = 0 /* 0. */;
            }
         }
      }
   }

   /* End execution of chart BVH2_Appl_Layer/Dry_RunningAlarm */

   /* Outport: BVH2_Appl_Layer/DryRunning */
   bool_DryRunningAlarm = Cb19_oDryRun66;

   /* Outport: BVH2_Appl_Layer/TemperatureAlarm */
   bool_CPU_TempAlarm = Cb51_oTempAlarm;

   /* Begin execution of chart BVH2_Appl_Layer/Current_Analysis_low */

   /* BVH2_Appl_Layer/Current_Analysis_low: Omitted comparison with constant. */
   if (SIBFS_Current_Analysis_low_b.Cb10_greenState) {
      /* Begin execution of state BVH2_Appl_Layer/Current_Analysis_low.greenState */

      /* # combined # update of inport for BVH2_Appl_Layer/Current_Analysis_low
         # combined # update of inport for BVH2_Appl_Layer/Current_Analysis_low */
      if (((Int32)ui16_mat_Current) > (ui16_Current_Thresh - 2)) {
         /* State transition from BVH2_Appl_Layer/Current_Analysis_low.greenState to BVH2_Appl_Layer
            /Current_Analysis_low.CntOverCurrent */
         SIBFS_Current_Analysis_low_b.Cb10_greenState = 0;
         SIBFS_Current_Analysis_low_b.Cb12_CntOverCurrent = 1;
         Cb9_StateCnt = 0 /* 0. */;
      }

      /* End execution of state BVH2_Appl_Layer/Current_Analysis_low.greenState */
   }
   else {
      /* BVH2_Appl_Layer/Current_Analysis_low: Omitted comparison with constant. */
      if (SIBFS_Current_Analysis_low_b.Cb11_Wait) {
         /* Begin execution of state BVH2_Appl_Layer/Current_Analysis_low.Wait */

         /* # combined # update of inport for BVH2_Appl_Layer/Current_Analysis_low
            # combined # update of inport for BVH2_Appl_Layer/Current_Analysis_low */
         if (((Int32)ui16_mat_Current) > (ui16_Current_Thresh - 2)) {
            /* State transition to BVH2_Appl_Layer/Current_Analysis_low.redState */
            SIBFS_Current_Analysis_low_b.Cb11_Wait = 0;
            SIBFS_Current_Analysis_low_b.Cb13_redState = 1;
            Cb9_oCurrentAlarm = 1;
         }
         else {
            if (Cb9_StateCnt > 100) {
               /* State transition to BVH2_Appl_Layer/Current_Analysis_low.greenState */
               SIBFS_Current_Analysis_low_b.Cb11_Wait = 0;
               SIBFS_Current_Analysis_low_b.Cb10_greenState = 1;
               Cb9_oCurrentAlarm = 0;
            }
            else {
               Cb9_StateCnt = Cb9_StateCnt + 1 /* 1. */;
            }
         }

         /* End execution of state BVH2_Appl_Layer/Current_Analysis_low.Wait */
      }
      else {
         /* BVH2_Appl_Layer/Current_Analysis_low: Omitted comparison with constant. */
         if (SIBFS_Current_Analysis_low_b.Cb12_CntOverCurrent) {
            /* Begin execution of state BVH2_Appl_Layer/Current_Analysis_low.CntOverCurrent */

            /* # combined # update of inport for BVH2_Appl_Layer/Current_Analysis_low
               # combined # update of inport for BVH2_Appl_Layer/Current_Analysis_low */
            if (((UInt32)ui16_mat_Current) < (ui16_Current_Thresh + 2)) {
               /* State transition to BVH2_Appl_Layer/Current_Analysis_low.greenState */
               SIBFS_Current_Analysis_low_b.Cb12_CntOverCurrent = 0;
               SIBFS_Current_Analysis_low_b.Cb10_greenState = 1;
               Cb9_oCurrentAlarm = 0;
            }
            else {
               if (Cb9_StateCnt > 50) {
                  /* State transition to BVH2_Appl_Layer/Current_Analysis_low.redState */
                  SIBFS_Current_Analysis_low_b.Cb12_CntOverCurrent = 0;
                  SIBFS_Current_Analysis_low_b.Cb13_redState = 1;
                  Cb9_oCurrentAlarm = 1;
               }
               else {
                  Cb9_StateCnt = Cb9_StateCnt + 1 /* 1. */;
               }
            }

            /* End execution of state BVH2_Appl_Layer/Current_Analysis_low.CntOverCurrent */
         }
         else {
            /* BVH2_Appl_Layer/Current_Analysis_low: Omitted comparison with constant. */
            if (SIBFS_Current_Analysis_low_b.Cb13_redState) {
               /* Begin execution of state BVH2_Appl_Layer/Current_Analysis_low.redState */

               /* # combined # update of inport for BVH2_Appl_Layer/Current_Analysis_low
                  # combined # update of inport for BVH2_Appl_Layer/Current_Analysis_low */
               if (((UInt32)ui16_mat_Current) < (ui16_Current_Thresh + 2)) {
                  /* State transition from BVH2_Appl_Layer/Current_Analysis_low.redState to BVH2_App
                     l_Layer/Current_Analysis_low.Wait */
                  SIBFS_Current_Analysis_low_b.Cb13_redState = 0;
                  SIBFS_Current_Analysis_low_b.Cb11_Wait = 1;
                  Cb9_StateCnt = 0 /* 0. */;
               }

               /* End execution of state BVH2_Appl_Layer/Current_Analysis_low.redState */
            }
            else {
               /* BVH2_Appl_Layer/Current_Analysis_low: Omitted comparison with constant. */
               if (!(SIBFS_Current_Analysis_low_b.Cb9_Current_Analysis_low)) {
                  SIBFS_Current_Analysis_low_b.Cb9_Current_Analysis_low = 1;

                  /* # combined # update of inport for BVH2_Appl_Layer/Current_Analysis_low */
                  if (ui8_ResetMatlab == 1) {
                     /* State transition to BVH2_Appl_Layer/Current_Analysis_low.greenState */
                     SIBFS_Current_Analysis_low_b.Cb10_greenState = 1;
                     Cb9_oCurrentAlarm = 0;
                  }
               }
            }
         }
      }
   }

   /* End execution of chart BVH2_Appl_Layer/Current_Analysis_low */

   /* Outport: BVH2_Appl_Layer/High_Current */
   bool_HighCurrentAlarm = Cb9_oCurrentAlarm;

   /* Outport: BVH2_Appl_Layer/PWMin_Alarm */
   bool_PWMin_err_Alarm = Cb34_oPWM_Alarm;

   /* Outport: BVH2_Appl_Layer/UbatAlarm */
   bool_UbatAlarm = Cb56_oUbat_Alarm_High;
   bool_MotorStalled = Cb24_oStalledAlarm || Cb1_oCurrentAlarm || Cb19_oDryRun55;

   /* Outport: BVH2_Appl_Layer/TemperatureRedAlarm */
   bool_CPU_TempRedAlarm = Cb51_oTempRedAlarm;

   /* Outport: BVH2_Appl_Layer/Debug */
   ui8_debug_out0 = (UInt8) Sb2_Switch5;
   Sb1_Logical_Operator3 = Sb1_Logical_Operator1 || Cb24_oMotorStalled || Cb14_oDryRunAlarm;
   Sb2_Logical_Operator2 = Sb1_Logical_Operator3 || bool_ControlLoopMode;
   if ((Sb2_Logical_Operator2 ^ X_Sb4_Intergrator_TriggerIn) && (!(Sb1_BVH2_Appl_Layer_FirstRun)))
    {
      X_Sb4_Intergrator = 80000 /* 100. */;
   }

   /* SwitchBVH2_Appl_Layer/Controller/Switch2
      BVH2_Appl_Layer/Controller/Switch2: Omitted comparison with constant. */
   if (Sb1_Logical_Operator3) {
      Sb2_Switch2 = 0 /* 0. */;
   }
   else {
      /* SwitchBVH2_Appl_Layer/Controller/Switch1
         BVH2_Appl_Layer/Controller/Switch1: Omitted comparison with constant. */
      if (bool_ControlLoopMode) {
         /* SwitchBVH2_Appl_Layer/Controller/Switch
            BVH2_Appl_Layer/Controller/Switch: Omitted comparison with constant. */
         if (Sb1_Logical_Operator5) {
            Sb2_Switch2 = Sb2_Fixed_Power;
         }
         else {
            /* SLLocal: Default storage class for local variables */
            UInt16 Sb3_Product1 /* LSB: 2^-8 OFF:  0 MIN/MAX:  0 .. 255.99609375 */;
            Int16 Sb3_Sum1;

            /* Product: BVH2_Appl_Layer/RangeAdaption/Product1
               BVH2_Appl_Layer/RangeAdaption/Product1: Constant was folded and saturated to the lowe
               r limit.
               
               # combined # Sum: BVH2_Appl_Layer/RangeAdaption/Sum2
               # combined # Sum: BVH2_Appl_Layer/RangeAdaption/Sum */
            Sb3_Product1 = (UInt16) (((UInt16) (140 /* 140. */ << 8)) / 160 /* 160. */);

            /* Sum: BVH2_Appl_Layer/RangeAdaption/Sum1
               # combined # Product: BVH2_Appl_Layer/RangeAdaption/Product2
               # combined # Sum: BVH2_Appl_Layer/RangeAdaption/Sum3
               # combined # Product: BVH2_Appl_Layer/RangeAdaption/Product3 */
            Sb3_Sum1 = (Int16) (((UInt16) ((((UInt32) ui8_PWM_dc_mat) * ((UInt32) Sb3_Product1)) >>
             8)) + ((Int16) (((Int16) (-((Int16) (UInt16) ((((UInt32) Sb3_Product1) * 95) >> 7)))) + 200)));

            /* # combined # Saturation: BVH2_Appl_Layer/Saturation */
            Sb2_Switch2 = (UInt16) C__U8SATI16_SATb(Sb3_Sum1, 200 /* 200. */, 60 /* 60. */);
         }
      }
      else {
         /* SLLocal: Default storage class for local variables */
         Int16 Sb4_PI_sum;

         /* Sum: BVH2_Appl_Layer/Controller/PID/PI_sum
            # combined # Discrete Integrator: BVH2_Appl_Layer/Controller/PID/Intergrator
            # combined # Product: BVH2_Appl_Layer/Controller/PID/Product1 */
         Sb4_PI_sum = (Int16) (((UInt16) (Int16) (X_Sb4_Intergrator / ((Int32) 800))) + ((UInt16)
          (Sb2_Error * ((Int16) ui8_Kp_mat))));

         /* # combined # Saturation: BVH2_Appl_Layer/Controller/PID/PI_Saturation */
         Sb2_Switch2 = C__U16SATI16_SATb(Sb4_PI_sum, 202 /* 202. */, 40 /* 40. */);
      }
   }

   /* Outport: BVH2_Appl_Layer/DutyCyclePowerStage
      # combined # Gain: BVH2_Appl_Layer/Gain */
   //ui8_duty_cycle_mat = (UInt8) (Int16) (Sb2_Switch2 >> 1);
   //if (Sb1_Logical_Operator3){  // used for overvoltage alarm
   /*UInt16 current_limit = 0;
   if (ui8_BattVolt_mat < 64){  //8V
       current_limit = 130;
   } else if (64 <= ui8_BattVolt_mat < 80){  //8-10V
       current_limit = 200;
   } else if (80 <= ui8_BattVolt_mat < 88){  //10-11V
       current_limit = 200;
   } else if (88 <= ui8_BattVolt_mat < 96){  //11-12V
       current_limit = 200;
   } else if (96 <= ui8_BattVolt_mat < 104){  //12-13V
       current_limit = 200;
   } else if (104 <= ui8_BattVolt_mat < 112){  //13-14V
       current_limit = 200;
   } else {  //14
       current_limit = 220;
   }
   if (ui16_mat_Current > current_limit){
       amps_per_volt_cnt = amps_per_volt_cnt + 1;
   }
   else {
       amps_per_volt_cnt = 0;
   }*/
   if (Sb1_Logical_Operator3 || power_lockout){
       ui16_duty_cycle_mat = 0;  // turn off pump
       power_lockout = 1;
   }
   else {
       ui16_duty_cycle_mat = ui16_Speed_demand_mat;  // bypass control loop
   }

   /* Outport: BVH2_Appl_Layer/Pump_off */
   bl_Pumpoff_Alarm = Sb1_Logical_Operator2;
   X_Sb4_Intergrator_TriggerIn = Sb2_Logical_Operator2;

   /* Discrete Integrator: integration
      # combined # Product: BVH2_Appl_Layer/Controller/PID/Product2 */
   X_Sb4_Intergrator = X_Sb4_Intergrator + ((Int32) (Int16) ((((Int16) ui8_Ki_mat) * Sb2_Error) <<
    3));

   /* Discrete Integrator: saturation */
   X_Sb4_Intergrator = C__I32SATI32_SATb(X_Sb4_Intergrator, 161600 /* 202. */, 32000 /* 40. */);

   /* BVH2_App_Layer/BVH2_Appl_Layer: Reset of the first run state */
   Sb1_BVH2_Appl_Layer_FirstRun = 0;
}

/*--------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*--------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Cb1_Current_An___High_node_fcn1
 *** 
 ***  DESCRIPTION:
 ***      Auxiliary function of Chart: BVH2_Appl_Layer/Current_Analysis_High
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      static Void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/ 
static Void Cb1_Current_An___High_node_fcn1(Void)
{
   /* BVH2_Appl_Layer/Current_Analysis_High: Omitted comparison with constant.
      # combined # update of inport for BVH2_Appl_Layer/Current_Analysis_High */
   if (bool_mat_currAlarm_bldc) {
      /* State transition to BVH2_Appl_Layer/Current_Analysis_High.CntOverCurrent */
      SIBFS_Current_Analysis_High_b.Cb1_Current_Analysis_High_ns = (unsigned int)
       Cb7_CntOverCurrent_id;
      Cb1_StateCnt = 0 /* 0. */;
      SIBFS_Current_Analysis_High_b.Cb1_glflag = 3 /* 3. */;
   }
   else {
      if (Cb1_StateCnt > 100) {
         /* State transition to BVH2_Appl_Layer/Current_Analysis_High.Alarm_Off */
         SIBFS_Current_Analysis_High_b.Cb1_Current_Analysis_High_ns = (unsigned int)
          Cb5_Alarm_Off_id;
         Cb1_oShutoff = 0;
         Cb1_oCurrentAlarm = 0;
         Cb1_RestartCounter = 0 /* 0. */;
         SIBFS_Current_Analysis_High_b.Cb1_glflag = 3 /* 3. */;
      }
      else {
         SIBFS_Current_Analysis_High_b.Cb1_glflag = 1 /* 1. */;
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Cb34_PWM_Detection_node_fcn1
 *** 
 ***  DESCRIPTION:
 ***      Auxiliary function of Chart: BVH2_Appl_Layer/PWM_Detection
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      static Void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/ 
static Void Cb34_PWM_Detection_node_fcn1(Void)
{
   if ((Cb34_idPWM < 1) || (Cb34_idPWM > 199)) {
       if (Cb34_idPWM > 199) {
        /* State transition to BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.CMD_MJP_0_100 */
        SIBFS_PWM_Detection_b.Cb35_PWMinput_handling_ns = (unsigned int) Cb40_CMD_MJP_0_100_id;
        Cb34_odPumpOff = 0;
        Cb34_odFixedValueSel = 1;
        Cb34_odFixedLowValueSel = 0;
        Cb34_oPWM_SC_Alarm = 0;
        Cb34_oPWM_Alarm = 1;
       }
   }
   else {
      /* # combined # update of inport for BVH2_Appl_Layer/PWM_Detection
         # combined # update of inport for BVH2_Appl_Layer/PWM_Detection */
      if ((ui16_PWM_Freq_mat < 36000) || (ui16_PWM_Freq_mat > 44000)) {
         /* State transition to BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.Alarm */
         SIBFS_PWM_Detection_b.Cb35_PWMinput_handling_ns = (unsigned int) Cb39_Alarm_id;
         Cb34_odPumpOff = 0;
         Cb34_odFixedValueSel = 1;
         Cb34_odFixedLowValueSel = 0;
         Cb34_oPWM_SC_Alarm = 1;
         Cb34_oPWM_Alarm = 0;
      }
      else {
         if (Cb34_idPWM <= 5) {
            /* State transition to BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.LimpModeLow */
            SIBFS_PWM_Detection_b.Cb35_PWMinput_handling_ns = (unsigned int) Cb36_LimpModeLow_id;
            Cb34_odPumpOff = 0;
            Cb34_odFixedValueSel = 1;
            Cb34_odFixedLowValueSel = 0;
            Cb34_oPWM_SC_Alarm = 1;
            Cb34_oPWM_Alarm = 0;
         }
         else {
            if (Cb34_idPWM < 9) {
               /* State transition to BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.LimpModeLow1
                */
               SIBFS_PWM_Detection_b.Cb35_PWMinput_handling_ns = (unsigned int)
                Cb37_LimpModeLow1_id;
               Cb34_odPumpOff = 1;
               Cb34_odFixedValueSel = 0;
               Cb34_odFixedLowValueSel = 0;
               Cb34_oPWM_SC_Alarm = 1;
               Cb34_oPWM_Alarm = 0;
            }
            else {
               if (Cb34_idPWM > 191) {
                  /* State transition to BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.SaturationH
                     igh */
                  SIBFS_PWM_Detection_b.Cb35_PWMinput_handling_ns = (unsigned int)
                   Cb38_SaturationHigh_id;
                  Cb34_odPumpOff = 0;
                  Cb34_odFixedValueSel = 1;
                  Cb34_odFixedLowValueSel = 0;
                  Cb34_oPWM_SC_Alarm = 1;
                  Cb34_oPWM_Alarm = 0;
               }
               else {
                  if (Cb34_idPWM >= 23) {
                     /* State transition to BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.Normal3
                      */
                     SIBFS_PWM_Detection_b.Cb35_PWMinput_handling_ns = (unsigned int)
                      Cb41_Normal3_id;
                     Cb34_odPumpOff = 0;
                     Cb34_odFixedLowValueSel = 0;
                     Cb34_odFixedValueSel = 0;
                     Cb34_oPWM_SC_Alarm = 0;
                     Cb34_oPWM_Alarm = 0;
                  }
                  else {
                     if (Cb34_idPWM > 19) {
                        /* State transition to BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.Satur
                           ationLow */
                        SIBFS_PWM_Detection_b.Cb35_PWMinput_handling_ns = (unsigned int)
                         Cb42_SaturationLow_id;
                        Cb34_odPumpOff = 0;
                        Cb34_odFixedValueSel = 0;
                        Cb34_odFixedLowValueSel = 1;
                        Cb34_oPWM_SC_Alarm = 0;
                        Cb34_oPWM_Alarm = 0;
                     }
                     else {
                        if (Cb34_idPWM <= 19) {
                           /* State transition to BVH2_Appl_Layer/PWM_Detection.PWMinput_handling.Pu
                              mpOff2 */
                           SIBFS_PWM_Detection_b.Cb35_PWMinput_handling_ns = (unsigned int)
                            Cb43_PumpOff2_id;
                           Cb34_odPumpOff = 1;
                           Cb34_odFixedValueSel = 0;
                           Cb34_odFixedLowValueSel = 0;
                           Cb34_oPWM_SC_Alarm = 0;
                           Cb34_oPWM_Alarm = 0;
                        }
                     }
                  }
               }
            }
         }
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Cb44_Pic_etat_monitor_node_fcn1
 *** 
 ***  DESCRIPTION:
 ***      Auxiliary function of Chart: BVH2_Appl_Layer/Pic_etat_monitor
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      static Void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/ 
static Void Cb44_Pic_etat_monitor_node_fcn1(Void)
{
   /* BVH2_Appl_Layer/Pic_etat_monitor: Omitted comparison with constant.
      # combined # update of inport for BVH2_Appl_Layer/Pic_etat_monitor */
   if (bool_mat_pic_etat) {
      /* State transition to BVH2_Appl_Layer/Pic_etat_monitor.Wrong_ETAT */
      SIBFS_Pic_etat_monitor_b.Cb44_Pic_etat_monitor_ns = (unsigned int) Cb49_Wrong_ETAT_id;
      Cb44_StateCnt = 0 /* 0. */;
      SIBFS_Pic_etat_monitor_b.Cb44_glflag = 3 /* 3. */;
   }
   else {
      if (Cb44_StateCnt > 5) {
         /* State transition to BVH2_Appl_Layer/Pic_etat_monitor.Alarm_Off */
         SIBFS_Pic_etat_monitor_b.Cb44_Pic_etat_monitor_ns = (unsigned int) Cb47_Alarm_Off_id;
         Cb44_oShutoff = 0;
         Cb44_oAlarm = 0;
         SIBFS_Pic_etat_monitor_b.Cb44_glflag = 3 /* 3. */;
      }
      else {
         SIBFS_Pic_etat_monitor_b.Cb44_glflag = 1 /* 1. */;
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Cb56_UbatHandling_node_fcn2
 *** 
 ***  DESCRIPTION:
 ***      Auxiliary function of Chart: BVH2_Appl_Layer/UbatHandling
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      static Void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/ 
static Void Cb56_UbatHandling_node_fcn2(Void)
{
   /* # combined # update of inport for BVH2_Appl_Layer/UbatHandling */
   if (((UInt8)ui8_BattVolt_mat) > 147) { /* was 230 */
      /* State transition to BVH2_Appl_Layer/UbatHandling.Ubat_Handling.SaturationHigh */
      switch (SIBFS_UbatHandling_b.Aux_sflag3) {
         case 2: {
            SIBFS_UbatHandling_b.Cb58_SaturationHigh = 0;
            break;
         }
         case 3: {
            SIBFS_UbatHandling_b.Cb59_SaturationLow = 0;
            break;
         }
         default: {
            SIBFS_UbatHandling_b.Cb60_NormalUbat = 0;
         }
      }
      SIBFS_UbatHandling_b.Cb58_SaturationHigh = 1;
      Cb56_odPumpOff = 1;
      Cb56_odFixedValueSel = 0;
      Cb56_oUbat_Alarm_High = 1;
   }
   else {
      switch (SIBFS_UbatHandling_b.Aux_sflag3) {
         case 2: {
            SIBFS_UbatHandling_b.Cb58_SaturationHigh = 0;
            break;
         }
         case 3: {
            SIBFS_UbatHandling_b.Cb59_SaturationLow = 0;
            break;
         }
         default: {
            SIBFS_UbatHandling_b.Cb60_NormalUbat = 0;
         }
      }

      /* # combined # update of inport for BVH2_Appl_Layer/UbatHandling */
      if (((UInt8)ui8_BattVolt_mat) < 45) {
         /* State transition to BVH2_Appl_Layer/UbatHandling.Ubat_Handling.SaturationLow */
         SIBFS_UbatHandling_b.Cb59_SaturationLow = 1;
         Cb56_odPumpOff = 1;
         Cb56_odFixedValueSel = 0;
         Cb56_oUbat_Alarm_High = 1;
      }
      else {
         /* State transition to BVH2_Appl_Layer/UbatHandling.Ubat_Handling.NormalUbat */
         SIBFS_UbatHandling_b.Cb60_NormalUbat = 1;
         Cb56_odPumpOff = 0;
         Cb56_odFixedValueSel = 0;
         Cb56_oUbat_Alarm_High = 0;
      }
   }
}


#endif/*_BVH2_APPL_LAYER_C_ */
/*--------------------------------------------------------------------*\
  END OF FILE
\*--------------------------------------------------------------------*/
