/**************************************************************************************************\
 *** 
 *** Simulink model       : BVH2_App_Layer
 *** TargetLink subsystem : BVH2_App_Layer/BVH2_Appl_Layer
 *** Codefile             : bvh2_appl_layer.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2015-06-22 15:49:18
 ***
 *** CODE GENERATOR OPTIONS:
 *** Compiler                            : <unknown>
 *** Target                              : Generic
 *** ANSI-C compatible code              : yes
 *** Optimization level                  : 2
 *** Constant style                      : decimal
 *** Clean code option                   : enabled
 *** Logging mode                        : Do not log anything
 *** Linker sections                     : enabled
 *** Assembler statements                : disabled
 *** Variable name length                : 31 chars
 *** Separate lookup search function     : disabled
 *** Use global bitfields                : disabled
 *** Stateflow: use of bitfields         : enabled
 *** State activity encoding limit       : 5
 *** Omit zero inits in restart function : disabled
 *** Share fcns between TL subsystems    : disabled
 *** Generate 64bit functions            : enabled
 *** Inlining Threshold                  : 6
 *** Line break limit                    : 100
 *** Target optimized boolean data type  : enabled
 *** Keep saturation elements            : disabled
 *** Extended variable sharing           : disabled
 *** Style definition file               : C:\Programme\dSPACE\Matlab\Tl\config\codegen\cconfig.xml
 *** Root style sheet                    : C:\Programme\dSPACE\Matlab\Tl\XML\CodeGen\Stylesheets\TL_
 ***                                       CSourceCodeSS.xsl
 *** Enable Multirate codegeneration     : disabled
 ***
 *** TargetLink version      : 2.0 from 22-Apr-2004
 *** Code generator version  : 2.0.0 build id 48 from 2004-04-22 13:23:03
 *** Copyright (c) 2004 dSPACE GmbH
\**************************************************************************************************/ 

#ifndef _BVH2_APPL_LAYER_H_
#define _BVH2_APPL_LAYER_H_

/*--------------------------------------------------------------------*\
  DEFINES (OPT)
\*--------------------------------------------------------------------*/
/*--------------------------------------------------------------------*\
  INCLUDES
\*--------------------------------------------------------------------*/
#include "tl_defines_b.h"
#include "tl_basetypes.h"
/*--------------------------------------------------------------------*\
  DEFINES
\*--------------------------------------------------------------------*/
/*--------------------------------------------------------------------*\
  TYPEDEFS
\*--------------------------------------------------------------------*/

struct tag_SIBFS_Current_Analysis_High_b_tp {
   unsigned int Cb1_Current_Analysis_High_ns : 4;
   unsigned int Cb1_glflag : 2;
   unsigned int Cb1_Current_Analysis_High : 1;
}; /* Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_Current_Analysis_low_b_tp {
   unsigned int Cb10_greenState : 1;
   unsigned int Cb11_Wait : 1;
   unsigned int Cb12_CntOverCurrent : 1;
   unsigned int Cb13_redState : 1;
   unsigned int Cb9_Current_Analysis_low : 1;
}; /* Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_Dry_RunningAlarm_b_tp {
   unsigned int Cb19_Dry_RunningAlarm : 1;
   unsigned int Cb20_greenState : 1;
   unsigned int Cb21_DryRunningAlarm : 1;
   unsigned int Cb22_DryRun66 : 1;
   unsigned int Cb23_DryRun55 : 1;
}; /* Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_Dry_Running_b_tp {
   unsigned int Cb14_Dry_Running : 1;
   unsigned int Cb15_greenState : 1;
   unsigned int Cb16_DryRunning : 1;
   unsigned int Cb17_redState : 1;
   unsigned int Cb18_CntOverCurrent : 1;
}; /* Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_Motor_Stalled_b_tp {
   unsigned int Cb25_Motor_sta__Statemachine_ns : 3;
   unsigned int Cb24_glflag : 2;
   unsigned int Cb24_Motor_Stalled : 1;
   unsigned int Cb25_Motor_stalled_Statemachine : 1;
   unsigned int Cb32_default : 1;
   unsigned int Cb33_Stop : 1;
}; /* Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_PWM_Detection_b_tp {
   unsigned int Cb35_PWMinput_handling_ns : 4;
   unsigned int Cb35_PWMinput_handling : 1;
}; /* Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_Pic_etat_monitor_b_tp {
   unsigned int Cb44_Pic_etat_monitor_ns : 3;
   unsigned int Cb44_glflag : 2;
   unsigned int Cb44_Pic_etat_monitor : 1;
}; /* Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_Temperature_Alarm_b_tp {
   unsigned int Cb51_Temperature_Alarm : 1;
   unsigned int Cb52_CntOverTemp : 1;
   unsigned int Cb53_reset : 1;
   unsigned int Cb54_greenTemp : 1;
   unsigned int Cb55_redTemp : 1;
}; /* Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_UbatHandling_b_tp {
   unsigned int Aux_sflag3 : 3;
   unsigned int Cb57_Ubat_Handling : 1;
   unsigned int Cb58_SaturationHigh : 1;
   unsigned int Cb59_SaturationLow : 1;
   unsigned int Cb60_NormalUbat : 1;
}; /* Type of structure containing bitfields for Stateflow chart  */
/*--------------------------------------------------------------------*\
  ENUMS
\*--------------------------------------------------------------------*/
/*--------------------------------------------------------------------*\
  VARIABLES
\*--------------------------------------------------------------------*/

/**********************************************************************\
   CONST: global constants (ROM)
\**********************************************************************/
extern CONST UInt16 Sb2_Fixed_Power;

/**********************************************************************\
   GLOBAL: global variables (RAM)
\**********************************************************************/
extern GLOBAL UInt16 ui16_Current_Thresh;
extern GLOBAL UInt16 ui16_PWM_Freq_mat;
extern GLOBAL UInt16 ui16_Speed_demand_mat;
extern GLOBAL UInt16 ui16_Speed_demand_mat_Max;
extern GLOBAL UInt16 ui16_Speed_demand_mat_min;
extern GLOBAL UInt16 ui16_Speed_mat;
extern GLOBAL UInt16 ui16_dryRun_Thresh;
extern GLOBAL UInt16 ui16_mat_Current;
extern GLOBAL UInt16 ui16_mat_inpTemp;
extern GLOBAL UInt16 ui8_BattVolt_mat;
extern GLOBAL UInt16 ui8_Ki_mat;
extern GLOBAL UInt16 ui8_fixed_start_speed_mat;
extern GLOBAL Bool bl_Pumpoff_Alarm;
extern GLOBAL Bool bool_CPU_TempAlarm;
extern GLOBAL Bool bool_CPU_TempRedAlarm;
extern GLOBAL Bool bool_ControlLoopMode;
extern GLOBAL Bool bool_DryRunningAlarm;
extern GLOBAL Bool bool_HighCurrentAlarm;
extern GLOBAL Bool bool_MotorStalled;
extern GLOBAL Bool bool_PIC_Alarm;
extern GLOBAL Bool bool_PWMin_Freq_err_Alarm;
extern GLOBAL Bool bool_PWMin_err_Alarm;
extern GLOBAL Bool bool_StalledMotorStop;
extern GLOBAL Bool bool_UbatAlarm;
extern GLOBAL Bool bool_mat_currAlarm_bldc;
extern GLOBAL Bool bool_mat_pic_etat;
extern GLOBAL Bool bool_start_demand_mat;
extern GLOBAL UInt8 ui8_Kp_mat;
extern GLOBAL UInt8 ui8_PWM_dc_mat;
extern GLOBAL UInt8 ui8_ResetMatlab;
extern GLOBAL UInt8 ui8_debug_out0;
extern GLOBAL UInt8 ui8_duty_cycle_mat;

/*--------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*--------------------------------------------------------------------*/
/*--------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*--------------------------------------------------------------------*/
/**********************************************************************\
   GlobalStep: Default function class for not static model step functions
\**********************************************************************/
extern Void BVH2_Appl_Layer(Void);


#endif/*_BVH2_APPL_LAYER_H_ */
/*--------------------------------------------------------------------*\
  END OF FILE
\*--------------------------------------------------------------------*/
