@echo off
rem *************************************************************
rem ** cleanup all files generated by TargetLink
rem *************************************************************

rem Simulink model name
set model=BVH2_App_Layer


rem Cleanup files created by the make procedure
if exist TLSim rmdir /s /q TLSim


if exist tl_types.h                   del tl_types.h
if exist tl_basetypes.h               del tl_basetypes.h
if exist tl_defines_b.h               del tl_defines_b.h
if exist BVH2_Appl_Layer.c            del BVH2_Appl_Layer.c
if exist BVH2_Appl_Layer.h            del BVH2_Appl_Layer.h

set tl_subsys=BVH2_Appl_Layer
if exist %tl_subsys%.c           del %tl_subsys%.c
if exist %tl_subsys%.h           del %tl_subsys%.h
if exist %tl_subsys%.a2l         del %tl_subsys%.a2l

if exist %tl_subsys%_udt.h       del %tl_subsys%_udt.h
if exist %tl_subsys%_lt.c        del %tl_subsys%_lt.c
if exist %tl_subsys%_lt.h        del %tl_subsys%_lt.h

if exist %tl_subsys%_sf.c        del %tl_subsys%_sf.c
if exist %tl_subsys%_sf.dll      del %tl_subsys%_sf.dll

rem cleanup files generated by TL Vs. < TL 2.0, if any 
if exist %tl_subsys%_info.m      del %tl_subsys%_info.m
if exist %tl_subsys%_new_info.m  del %tl_subsys%_new_info.m
if exist %tl_subsys%_frm.h       del %tl_subsys%_frm.h
if exist %tl_subsys%_pcf.c       del %tl_subsys%_pcf.c
if exist %tl_subsys%_sfh.c       del %tl_subsys%_sfh.c
if exist %tl_subsys%_sfh.dll     del %tl_subsys%_sfh.dll
if exist %tl_subsys%_sfh.pdb     del %tl_subsys%_sfh.pdb
if exist %tl_subsys%_sft.c       del %tl_subsys%_sft.c
if exist %tl_subsys%_sft.dll     del %tl_subsys%_sft.dll
if exist %tl_subsys%_sft.pdb     del %tl_subsys%_sft.pdb
if exist %tl_subsys%.lis         del %tl_subsys%.lis

rem cleanup model specific files
if exist %model%_ts.c           del %model%_ts.c
if exist %model%.mk             del %model%.mk
if exist %model%_ts.a2l         del %model%_ts.a2l
if exist %model%_ts_symbols.m   del %model%_ts_symbols.m
if exist ProductionCode.dll     del ProductionCode.dll

rem cleanup documentation files
if exist *.html                   del *.html
if exist *.png                    del *.png
if exist *.jpg                    del *.jpg

rem cleanup ASAP2 files
if exist *.a2l                    del *.a2l

rem cleanup other files
if exist tl_autoscaling.log       del tl_autoscaling.log
if exist lnk*.tmp                 del lnk*.tmp
if exist make*.lck                del make*.lck
if exist vc40.pdb                 del vc40.pdb
if exist vc50.pdb                 del vc50.pdb

if exist BS_Debug.txt             del BS_Debug.txt
if exist hdi.hdc                  del hdi.hdc
if exist hdi.hds                  del hdi.hds

set model=
set tl_subsys=
